### ISSUE TITLE
Use -noautorotate with jave2

### ISSUE THREAD

**Issue by vspirit777** [a-schild/jave2#107]
Hi,
Is there any way to use -noautorotate option in jave2?

**Comment by mressler** [comment]
Version 3+ support adding arbitrary options to the `Encoder`. @a-schild would speak to release dates.

**Comment by vspirit777** [comment]
Cool, thank you

**Comment by vspirit777** [comment]
Hi @a-schild , Could you please tell us release date for version 3+?

**Comment by a-schild** [comment]
Is released

**Comment by vspirit777** [comment]
Hi @a-schild @mressler is there any example for adding arbitrary options to the Encoder?

**Comment by mressler** [comment]
@vspirit777 Do you still need an example?

In case anyone finds this in the future, check out the [`Encoder`](https://github.com/a-schild/jave2/blob/master/jave-core/src/main/java/ws/schild/jave/Encoder.java#L354) class. The `addOptionAtIndex()` method is intended to be how you insert into that `globalOptions` array.

**Comment by vspirit777** [comment]
@mressler Thanks for the support, I found that method and tested, it worked as expected. Thanks
