### ISSUE TITLE
Is it possible to create a video from images?

### ISSUE THREAD

**Issue by SarmadSA** [a-schild/jave2#108]
Hi,

Before I use this library, I have a question.
I read that this library is used to"transcode audio and video files from a format to another", is that all it does or is it possible to generate a video from images like ffmpeg does? or is it not as powerful as ffmpeg? I also want to add text to the video, and maybe zoom in the images while the video is playing (but this is not a requirement).

**Comment by mressler** [comment]
This library is a utility that interfaces with `ffmpeg`. It does not do any of the transcoding - it is meant to be a utility for accessing and interacting with `ffmpeg`.

`ffmpeg` would accomplish this with the movie filter, so does JAVE. See the [`MovieFilter`](https://github.com/a-schild/jave2/blob/dev-3.0-changes/jave-core/src/main/java/ws/schild/jave/filters/MovieFilter.java) class in JAVE. For example usage, see the [tests](https://github.com/a-schild/jave2/blob/dev-3.0-changes/jave-core-test/src/test/java/ws/schild/jave/filters/VideoFilterTest.java#L163) for related filters (such as the overlay filter).
