### ISSUE TITLE
Exit code of ffmpeg encoding run is 1

### ISSUE THREAD

**Issue by vishnukrazybee** [a-schild/jave2#109]
Exception in thread "main" ws.schild.jave.EncoderException: Exit code of ffmpeg encoding run is 1
	at ws.schild.jave.Encoder.encode(Encoder.java:691)
	at ws.schild.jave.Encoder.encode(Encoder.java:398)
	at ws.schild.jave.Encoder.encode(Encoder.java:363)
	at com.digitap.entSpecificRequirement.service.CompressAndChangeFormatService.compressAndChangeFormat(CompressAndChangeFormatService.java:55)
	at com.digitap.entSpecificRequirement.service.StitchVideoService.stitchVideos(StitchVideoService.java:88)
	at com.digitap.entSpecificRequirement.Test.main(Test.java:19)

`package com.digitap.entSpecificRequirement.service;

import lombok.extern.slf4j.Slf4j;
import ws.schild.jave.*;

import java.io.File;

@Slf4j
public class CompressAndChangeFormatService {

    private static CompressAndChangeFormatService compressAndChangeFormatService;

    private CompressAndChangeFormatService() {

    }

    public static CompressAndChangeFormatService getInstance() {
        if (compressAndChangeFormatService == null) {
            synchronized (CompressAndChangeFormatService.class) {
                if (compressAndChangeFormatService == null) {
                    log.info("creating an instance of compress and change format service");
                    compressAndChangeFormatService = new CompressAndChangeFormatService();
                }
            }
        }
        return compressAndChangeFormatService;
    }

    public void compressAndChangeFormat(String format, int videoFps, String actualPath, String alteredPath) throws Exception {
        log.info("in compressAndChangeFormat with format {} video fps {} actual path {} altered file path {}"
                , format, videoFps, actualPath, alteredPath);
        File actualFilePath = new File(actualPath);
        log.info("actual file path is {}", actualFilePath.getAbsolutePath());
        File alteredFilePath = new File(alteredPath);
        if (alteredFilePath.mkdir() || alteredFilePath.createNewFile()) {
            log.info("creating a new file with path {} for altered file", alteredFilePath.getAbsolutePath());
        }
        AudioAttributes audio = new AudioAttributes();

        VideoAttributes video = new VideoAttributes();
        video.setX264Profile(VideoAttributes.X264_PROFILE.BASELINE);
        video.setFrameRate(videoFps);
        video.setSize(new VideoSize(640, 480));
        log.info("audio is {} video is {}", audio, video);

        EncodingAttributes encodingAttributes = new EncodingAttributes();
        encodingAttributes.setFormat(format);
        encodingAttributes.setAudioAttributes(audio);
        encodingAttributes.setVideoAttributes(video);
        log.info("encoding attributes is {}", encodingAttributes);

        long startTime = System.currentTimeMillis();
        MultimediaObject multimediaObject = new MultimediaObject(actualFilePath);
        Encoder encoder = new Encoder();
        encoder.encode(multimediaObject, alteredFilePath, encodingAttributes);
        log.info("the video has changed its format successfully time taken is {}", (System.currentTimeMillis() - startTime));
    }
}
`

**Comment by mressler** [comment]
Can you share what the warning output of `ffmpeg` was? There are a lot of reasons that `ffmpeg` will error and it does a pretty good job explaining why in its warning output.

**Comment by mressler** [comment]
I plan on closing this issue in a few days unless we get some more information. At the moment I can't tell if this is a JAVE issue or misuse of `ffmpeg`.

**Comment by vishnukrazybee** [comment]
Hi @mressler sorry for late reply,the above code is working fine

**Comment by N0153128** [comment]
@vishnuvijaypr could you please share what the original issue was and how you've fixed it?

**Comment by N0153128** [comment]
finally got to the bottom of this. for some reason, having jave-all-deps installed - doesn't prevent the dev from having various slf4j related issues.

i was able to find out what my problem was by adding slf4j-api and slf4j-simple to my project's pom file like so:

        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version><LATEST VERSION HERE></version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version><LATEST VERSION HERE></version>
        </dependency>

in my case, i was using an incorrect set of codecs for my re-encoding purposes. i was also giving a lossless flac media a bitrate parameter, which was my mistake.
surprisingly, as @mressler mentioned - slf4j does indeed a great job at telling the dev what the issue is. would be nice to have slf4j shipped along with jave-all-deps.
