### ISSUE TITLE
Not an issue... But when can we expect this in Maven central???

### ISSUE THREAD

**Issue by ArunPrasathSubramani** [a-schild/jave2#11]
Thanks for this effor @a-schild ... You are a life-saver :+1: . Can we know, when you have planed to get it on Maven central?

Thanks again.

**Comment by goxr3plus** [comment]
Hello my friend i have forked the repository and published with Jitpack,
chsck the issue here inhave the answer for you, already i am using the
latest version of library :


https://github.com/a-schild/jave2/issues/10

**Comment by goxr3plus** [comment]
The repository now if officially on Maven central.

**Comment by goxr3plus** [comment]
Check the issue #10 Andrea project owner has given the code
