### ISSUE TITLE
ws.schild.jave.EncoderException: Exit code of ffmpeg encoding run is 1. Trying make an 160Bit mp3 to 16Bit MP3

### ISSUE THREAD

**Issue by juferdinand** [a-schild/jave2#112]
Hello,
I tried in my Freetime to make and 160Bit mp3 to 16Bit Mp3 and got an error
[Error.txt](https://github.com/a-schild/jave2/files/5115992/Error.txt)

My Code is this:      

    MultimediaObject multimediaObject = new MultimediaObject(new File("file.mp3"));
        File target = new File("file2.mp3");
        AudioAttributes audio = new AudioAttributes();
        audio.setCodec("pcm_s16le");
        audio.setBitRate(16);
        audio.setChannels(1);
        audio.setSamplingRate(8000);
        EncodingAttributes attrs = new EncodingAttributes();
        attrs.setFormat("mp3");
        attrs.setAudioAttributes(audio);
        Encoder encoder = new Encoder();
        try {
            encoder.encode(multimediaObject, target, attrs);
            System.out.println("Successfully created");
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

I use the newest ffmpeg.

I hope anyone can help me

greetings 
juferdinand

**Comment by a-schild** [comment]
As the error message tells you, 16bit as audio bitrate is to low to have any real audio in the stream.
Are you sure you need an 16bit and not a 16kBit rate?

**Comment by juferdinand** [comment]
Yea I mean 16kBit sorry was my failure. You know what I do false 😅

**Comment by a-schild** [comment]
Perhaps change

`audio.setBitRate(16);`
to
`audio.setBitRate(16000);`
?

**Comment by juferdinand** [comment]
It worked not, same Error like before. I did any other fail maybe or forgot I anything?

09:35:19.499 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (2): <  Duration: 00:00:32.76, start: 0.025057, bitrate: 160 kb/s>
09:35:19.499 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (3): <    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 160 kb/s>
09:35:19.499 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (4): <    Metadata:>
09:35:19.499 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (5): <      encoder         : LAME3.100>
09:35:19.499 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (6): <Stream mapping:>
09:35:19.499 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (7): <  Stream #0:0 -> #0:0 (mp3 (mp3float) -> pcm_s16le (native))>
09:35:19.499 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (8): <Press [q] to stop, [?] for help>
09:35:19.499 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (9): <[mp3 @ 000001e71b2518c0] Invalid audio stream. Exactly one MP3 audio stream is required.>
09:35:19.499 [main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 2 Line: 9 message: <[mp3 @ 000001e71b2518c0] Invalid audio stream. Exactly one MP3 audio stream is required.>
09:35:19.499 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (10): <Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument>
09:35:19.499 [main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 2 Line: 10 message: <Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument>
09:35:19.499 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (11): <Error initializing output stream 0:0 -- >
09:35:19.499 [main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 2 Line: 11 message: <Error initializing output stream 0:0 -- >
09:35:19.499 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (12): <Conversion failed!>
09:35:19.499 [main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 2 Line: 12 message: <Conversion failed!>
09:35:19.500 [main] ERROR ws.schild.jave.Encoder - Process exit code: 1  to file2.mp3
ws.schild.jave.EncoderException: Exit code of ffmpeg encoding run is 1
	at ws.schild.jave.Encoder.encode(Encoder.java:691)
	at ws.schild.jave.Encoder.encode(Encoder.java:398)
	at ws.schild.jave.Encoder.encode(Encoder.java:363)
	at de.bitrate.changer.ChangerApplication.main(ChangerApplication.java:29)

**Comment by a-schild** [comment]
Looks like somehting is wrong with your audio file

` Invalid audio stream. Exactly one MP3 audio stream is required.`

**Comment by juferdinand** [comment]
But this Audiofile works if I wanna hear it, it works without Problems. i copied this code from Stackoverflow there the Guy used an .wav data, is this the Problem? If yes how I can solve this Problem, have u any Idea there?

**Comment by a-schild** [comment]
Since this error is input file dependent, we would need to get hold of the input file so see what's the problem.

**Comment by juferdinand** [comment]
This is the File but is it on my Mainlanguage German, just an random file from the Internet to test it 😅 


[file.zip](https://github.com/a-schild/jave2/files/5116750/file.zip)

**Comment by juferdinand** [comment]
Hello? Have u no Idea?
Wanna finish this Project and anything what I try goes in Error

**Comment by mressler** [comment]
When you run just `ffmpeg -i yourAudioFile.mp3` what is the result?

**Comment by a-schild** [comment]
I did try your code, and it struggels with this argument:

`audio.setCodec("pcm_s16le");`

If you comment this line out, the conversion works.
Is there a specific reason your need `pcm_s16le`?

**Comment by mressler** [comment]
This looks like JAVE is faithfully relaying the users' commands to `ffmpeg`.

I suggest closing any issue that should instead be directed to an `ffmpeg` support board. I'd rather not have issues filed against JAVE that are "How do I do this thing on `ffmpeg`?"

I'll leave this here for a few days before I close similar issues.

**Comment by juferdinand** [comment]
It works without this line perfect, I don't know what the Problem is there 😅 

But now it works without Problem, I needed this Line not.

Can I the Log Output make much smaller? I get fully Debug Log also if I run without Debug

**Comment by mressler** [comment]
What line are you referring to? Are you able to get this to work when you call `ffmpeg` by command line directly?

**Comment by a-schild** [comment]
You have to configure your logging framework correctly, there you can tell the system what logging level you wish to have
