### ISSUE TITLE
Could not find ffmpeg platform executable in resources for <ws/schild/jave/nativebin/ffmpeg-amd64

### ISSUE THREAD

**Issue by vspirit777** [a-schild/jave2#115]
Hi,
Currently when run java by command line, I saw this error:
Could not find ffmpeg platform executable in resources for <ws/schild/jave/nativebin/ffmpeg-amd64
and can't create file /tmp/jave/ffmpeg-amd64-3.0.0, please help check.

And if I run in Idea Intelliji, it works fine.

**Comment by vspirit777** [comment]
I checked .jar file, it included jave-nativebin-linux64-3.0.0 also:
![image](https://user-images.githubusercontent.com/6006585/91427962-8606a480-e888-11ea-965a-cc00e9ad4e31.png)

**Comment by a-schild** [comment]
So you probably are missing the jar specifications when you run it on the commandline.
In the classpath you must list all jars which are used or work with a manifest

**Comment by vspirit777** [comment]
Hi, all jars was included in main jar already, I use SpringBoot framework with gradle, it build into one big jar include all neccessary jars. And when I juse old version (jave 2.7.1) it work fine, the problem just with new version in my case

**Comment by vspirit777** [comment]
Currently I have workaround solution:
var file = this.getClass().getClassLoader()
        .getResourceAsStream("ws/schild/jave/nativebin/ffmpeg-amd64")
and copy the file to /tmp/jave, it works.

**Comment by vspirit777** [comment]
More information: the below code in DefaultFFMPEGLocator.java is not working, is is still null:
`LOG.debug("Copy from resource <{}> to target <{}>", resourceName, dest.getAbsolutePath());
      InputStream is = getClass().getResourceAsStream(resourceName);
      if (is == null) {
        // Use this for Java 9+ only if required
        resourceName = "ws/schild/jave/nativebin/" + path;
        LOG.debug(
            "Alternative copy from SystemResourceAsStream <{}> to target <{}>",
            resourceName,
            dest.getAbsolutePath());
        is = ClassLoader.getSystemResourceAsStream(resourceName);
      }`

**Comment by a-schild** [comment]
WHat java version are you using?

**Comment by vspirit777** [comment]
I'm using java 11

**Comment by a-schild** [comment]
For me it's working also with java14...
Any chance you can make a small reproducable example?

Since t works in ItteliJ, it has something to do with your (project) environment.

As long as I can't reproduce it, I have no chance to fix it

**Comment by vspirit777** [comment]
Sorry for late response, I will setup another project and send you when I have time.

**Comment by fanweihua** [comment]
I had the same issue when I deploy my springboot project to centos7. It works fine on my dev osx computer

**Comment by a-schild** [comment]
As mentioned, please make a small demo project where you can reproduce the problem

**Comment by fanweihua** [comment]
[demo.zip](https://github.com/a-schild/jave2/files/5173366/demo.zip)
This is springboot demo with one api to detect audio duration.
Steps to reproduce:
1. Compile and package
`mvn clean package`
2. Run as a service
`java -jar demo-0.0.1-SNAPSHOT.jar`
3. post a request to the service
`{
    "url": "https://..../test.wav"
}`

Here is the log on osx:
`ws.schild.jave.EncoderException: java.io.IOException: Cannot run program "/var/folders/1z/gcdj8fl50p3131jl_s7nl3g40000gn/T/jave/ffmpeg-x86_64-3.0.0-osx": error=2, No such file or directory
	at ws.schild.jave.MultimediaObject.getInfo(MultimediaObject.java:157) ~[jave-core-3.0.0.jar!/:na]
	at com.example.demo.service.DemoService.getDuration(DemoService.java:24) ~[classes!/:0.0.1-SNAPSHOT]
	at com.example.demo.controller.DemoController.getDuration(DemoController.java:18) [classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_192]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_1`

**Comment by a-schild** [comment]
Ok,

can you please try with java 3.0.1-SNAPSHOT ?

**Comment by fanweihua** [comment]
3.0.1-SNAPSHOT works. Thanks.
Tested on both OSX and CentOS7.
I don't have Windows workstation so didn't try on Windows.

**Comment by a-schild** [comment]
3.0.1 is now released

**Comment by fanweihua** [comment]
It seems linux64 build is missing.
`Could not find artifact ws.schild:jave-nativebin-linux64:pom:3.0.1 in central (https://repo.maven.apache.org/maven2)`

**Comment by a-schild** [comment]
Ooopppsss,
yes, it was missing (And laso the win32 binary)
It's now fixed, but make tyke a few hours until  the maven repos are all updated

**Comment by Programmist-Futurist** [comment]
Exception in thread "main" ws.schild.jave.EncoderException: java.io.IOException: Cannot run program "/tmp/jave/ffmpeg-amd64-3.0.1": error=2, No such file or directory
	at ws.schild.jave.Encoder.getCoders(Encoder.java:173)
	at ws.schild.jave.Encoder.getAudioEncoders(Encoder.java:125)


File "/tmp/jave/ffmpeg-amd64-3.0.1" is missing =(

**Comment by Programmist-Futurist** [comment]
Ohhhh, Sory, I had wrong dependency. Now it's ok))

**Comment by andrebrz** [comment]
> Ohhhh, Sory, I had wrong dependency. Now it's ok))

Hello! How did you solve this problem? I'm facing the same thing here...

**Comment by a-schild** [comment]
What platform are you running on and what dependencie(s) have you in your pom.xml?

**Comment by gm100861** [comment]
upgrade to 3.0.1 can fixed this issue.

**Comment by unk1911** [comment]
i'm on 3.5.0 and still have this annoying issue. i have to manually relink the reference to ffmpeg in /tmp/jave2/   to /usr/bin/ffmpeg every time i upgrade to a new version...
