### ISSUE TITLE
Could we support to get more meta data from video in MultimediaInfo object

### ISSUE THREAD

**Issue by vspirit777** [a-schild/jave2#116]
Hi,
Currently, I need to get "rotate" field to know video orientation is in portrait or landscape, and maybe some another attributes, could you support this? Thank you

**Comment by mressler** [comment]
Can you be more specific in your request? I don't know what the rotate field is or where I'd get it. Is this something that is output from `ffmpeg` when you give it an input file?

**Comment by a-schild** [comment]
I think he means the rotation/orientation of the video recording accorning to this:

https://superuser.com/questions/660505/find-out-rotation-metadata-from-video-in-ffmpeg

**Comment by vspirit777** [comment]
Alright, rotate field will occurs in some videos and determinate orientation of video:
![image](https://user-images.githubusercontent.com/6006585/92068114-3c5e1280-edd0-11ea-963a-ccb2afe4ad29.png)

**Comment by mressler** [comment]
Yes, that field will be in the metadata object when I refactor parsing.

**Comment by vspirit777** [comment]
Cool, thanks so much @mressler . Is there any plan for the release date?

**Comment by mressler** [comment]
Not currently, still in the beginning stages of the refactor.

**Comment by vspirit777** [comment]
Oops, I really need it for our project

**Comment by a-schild** [comment]
@vspirit777 It's an opensource project, so you can also contribute to it.
If you wish to sponsor this development, then we can priorize the things you require

**Comment by gemy21ce** [comment]
@a-schild I believe it's the step is moving forward once it reads first metadata 
https://github.com/a-schild/jave2/blob/master/jave-core/src/main/java/ws/schild/jave/MultimediaObject.java#L211
Do you have any sort of rules for contribution?

**Comment by a-schild** [comment]
No special rules, but please write test cases for the functionality you contribute and/or modify

**Comment by gunrosen** [comment]
I tested with my video with version 3.1.1
It only get metadata in step=1. So metadata in "Video" or "Audio" will not be collected.

![image](https://user-images.githubusercontent.com/3174484/125565408-34962c68-7089-403f-b328-4c8525f37c6c.png)
![image](https://user-images.githubusercontent.com/3174484/125567194-1687de1c-f2a5-47ed-9e42-082f07d28151.png)

**Comment by gunrosen** [comment]
Sorry, my mistake, version 3.1.1 does not have sources about metadata. Could you build new version?

**Comment by a-schild** [comment]
Could you please try with 3.2.0-SNAPSHOT
If it's ok for you, then I will release it

**Comment by gunrosen** [comment]
@a-schild I built jave-core and import with pom
```
		<dependency>
			<groupId>ws.schild</groupId>
			<artifactId>jave-all-deps</artifactId>
			<version>3.1.1</version>
		</dependency>

		<dependency>
			<groupId>ws.schild</groupId>
			<artifactId>jave-core</artifactId>
			<version>3.2.0-SNAPSHOT</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/src/lib/jave-core-3.2.0-SNAPSHOT.jar</systemPath>
		</dependency>
```
It is OK to get metadata now, thanks
<img width="1351" alt="Screen Shot 2021-07-15 at 10 47 30" src="https://user-images.githubusercontent.com/3174484/125726182-a72216db-7683-47d8-b25b-dbca93609ff7.png">

**Comment by gemy21ce** [comment]
@a-schild would you please release a new version?

**Comment by gemy21ce** [comment]
@a-schild if you can share you release steps, I can help you releasing a new version!

**Comment by a-schild** [comment]
3.2.0 is now released
