### ISSUE TITLE
pcm 2 mp3 ws.schild.jave.InputFormatException: Invalid data found when processing input

### ISSUE THREAD

**Issue by caocharlie** [a-schild/jave2#118]
`
<dependency>
            <groupId>ws.schild</groupId>
            <artifactId>jave-all-deps</artifactId>
            <version>3.0.1</version>
</dependency>
`

code:
`
EncodingAttributes attrs = new EncodingAttributes();

//Audio Attributes
AudioAttributes audio = new AudioAttributes();
audio.setCodec("libmp3lame");
attrs.setAudioAttributes(audio);

attrs.setInputFormat("s16be -acodec pcm_s16le -ac 2 -ar 16000");
attrs.setSafe(1);

//Encode
Encoder encoder = new Encoder();
encoder.encode(new MultimediaObject(source), target, attrs);
`

error msg:

ws.schild.jave.InputFormatException: Invalid data found when processing input
	at ws.schild.jave.MultimediaObject.parseMultimediaInfo(MultimediaObject.java:217)
	at ws.schild.jave.MultimediaObject.getInfo(MultimediaObject.java:165)
	at ws.schild.jave.Encoder.encode(Encoder.java:534)
	at ws.schild.jave.Encoder.encode(Encoder.java:351)
	at ws.schild.jave.Encoder.encode(Encoder.java:318)

but run command created by the code in termail it`s success.

command:
/var/folders/0m/w1njychs47v_5j0j35mg_8v80000gn/T/jave/ffmpeg-x86_64-3.0.1-osx -f s16be -acodec pcm_s16le -ac 2 -ar 16000 -i /Users/abc/Downloads/16k_10.pcm -vn -acodec libmp3lame -y /Users/abc/Downloads/16k_10.mp3 -hide_banner

**Comment by a-schild** [comment]
Since this is probably related to the input file, we would need the input file too

**Comment by caocharlie** [comment]
[4f4d7646f42511ea_1.pcm.zip](https://github.com/a-schild/jave2/files/5215819/4f4d7646f42511ea_1.pcm.zip)
this is the pcm file.
3Q

**Comment by caocharlie** [comment]
the ffmpeg info:

ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.8)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-appkit --enable-avfoundation --enable-coreimage --enable-audiotoolbox
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100

**Comment by a-schild** [comment]
Your inputfile is corrupt.

When doing this:

`ffmpeg    -f s16be -acodec pcm_s16le -ac 2 -ar 16000 -i 4f4d7646f42511ea_1.pcm   out.wav`

Then ffmpeg shows:

```
[s16be @ 001ecee0]Estimating duration from bitrate, this may be inaccurate
Input #0, s16be, from '4f4d7646f42511ea_1.pcm':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0.0: Audio: pcm_s16le, 16000 Hz, 2 channels, s16, 512 kb/s
Output #0, wav, to 'out.wav':
  Metadata:
    encoder         : Lavf52.67.0
    Stream #0.0: Audio: pcm_s16le, 16000 Hz, 2 channels, s16, 512 kb/s
Stream mapping:
  Stream #0.0 -> #0.0
Press [q] to stop encoding
Multiple frames in a packet from stream 0
[pcm_s16le @ 001ede80]invalid PCM packet
**Error while decoding stream #0.0**
size=     115kB time=1.84 bitrate= 512.2kbits/s
video:0kB audio:115kB global headers:0kB muxing overhead 0.037416%
```

So the error thrown by jave is "correct", even when ffmpeg trys to do the best of the situation.
Are other pcm files showing the same behaviour?

**Comment by mressler** [comment]
Closing as stale. Share details if you're getting an error from JAVE that isn't also produced by `ffmpeg` and that's something we can take a look at.
