### ISSUE TITLE
Can I use it change Mp4 vedioto multiple fragments?

### ISSUE THREAD

**Issue by Beginner-yms** [a-schild/jave2#119]
Can I use it change Mp4 vedioto multiple fragments?
I don't find demo in code.

**Comment by a-schild** [comment]
Have you an example how you do it with ffmpeg?

**Comment by Beginner-yms** [comment]
like this :ffmpeg -i test.mp4 -f segment -segment_time 60 -segment_format_options movflags=+faststart out%03d.mp4

**Comment by mressler** [comment]
The `Encoder` can produce arbitrary output options to the `ffmpeg` executable.

See the [`Encoder.addOptionAtIndex`](https://github.com/a-schild/jave2/blob/master/jave-core/src/main/java/ws/schild/jave/Encoder.java#L440) method. This is a common enough response, we should probably put an example in the README.

**Comment by Beginner-yms** [comment]
Thank you!
