### ISSUE TITLE
Convert .wma to mp3 failed

### ISSUE THREAD

**Issue by TangTing528** [a-schild/jave2#12]
Using the following attributes to convert .wma to .mp3 failed:

File source = new File("source.wav");
File target = new File("target.mp3");
AudioAttributes audio = new AudioAttributes();
audio.setCodec("libmp3lame");
audio.setBitRate(new Integer(128000));
audio.setChannels(new Integer(2));
audio.setSamplingRate(new Integer(44100));
EncodingAttributes attrs = new EncodingAttributes();
attrs.setFormat("mp3");
attrs.setAudioAttributes(audio);
Encoder encoder = new Encoder();
encoder.encode(source, target, attrs);

The error:

[libmp3lame @ 0000000000500340] Queue input is backward in time

**Comment by goxr3plus** [comment]
Well wait which version of library are you using?

Try the latest one, it's working pretty good :

Add it with Maven like is shown here:

https://github.com/a-schild/jave2/issues/10

**Comment by a-schild** [comment]
Can you please retry it with the 2.4.0 release?
The 2.3.x had a bug in audio conversions

**Comment by TangTing528** [comment]
I'm using the code from github directly. Some of the wma files can be convert without throwing exception and some are not. After I post the issue, I tried to convert the file by commenting out the throwing exception part (Line 638 in Encode.java). Then it works fine. The files have been successfully converted to mp3. I do not know how it works, but I'm glad it works.

Thanks so much!!!!!

**Comment by a-schild** [comment]
Hello @TangTing528 ,

can you please provide me one such wav file which fails to convert correctly?

**Comment by TangTing528** [comment]
Sorry, the .wma files I use contains PII(personal identificaiton information). I cannot share them with  you.

**Comment by a-schild** [comment]
Since the error depends on the input file, I have no way to track down the error.
Could you in some way fill the audio file with noise, so you can send me the file?

**Comment by TangTing528** [comment]
Accually, I'm getting the data from database as a blob and store it to as file in local, then use the program to convert it to mp3. So maybe there is something wrong when I convert the blob to file.

Right now, it works when I comment out the throw the error part. So thank you so much for following up  the issue.

**Comment by ArunPrasathSubramani** [comment]
Hi @a-schild , I work with Ting, As she mentioned we cannot share the file. 
But I have the logs which might help you fugure out the issue. The bolded line is where the exception was thrown earlier. We commented the line throwing the error and it works like a champ now. 
Thanks again for the project.

ws.schild.jave.MultimediaObject - Output line: Input #0, asf, from '<<input File location>>':
ws.schild.jave.MultimediaObject - Output line:   Metadata:
ws.schild.jave.MultimediaObject - Output line:     WMFSDKNeeded    : 0.0.0.0000
ws.schild.jave.MultimediaObject - Output line:     DeviceConformanceTemplate: S1
ws.schild.jave.MultimediaObject - Output line:     WMFSDKVersion   : 11.0.6002.18049
ws.schild.jave.MultimediaObject - Output line:     IsVBR           : 0
ws.schild.jave.MultimediaObject - Output line:   Duration: 00:00:04.32, start: 0.000000, bitrate: 15 kb/s
ws.schild.jave.MultimediaObject - Output line:     Stream #0:0(eng): Audio: wmavoice ([10][0][0][0] / 0x000A), 8000 Hz, mono, flt, 4 kb/s
ws.schild.jave.MultimediaObject - Output line: At least one output file must be specified
ws.schild.jave.MultimediaObject - Output line: null
ws.schild.jave.Encoder - Input Line (1): Input #0, asf, from '<<input File location>>':
ws.schild.jave.Encoder - Input Line (2):   Metadata:
ws.schild.jave.Encoder - Input Line (3):     WMFSDKNeeded    : 0.0.0.0000
ws.schild.jave.Encoder - Input Line (4):     DeviceConformanceTemplate: S1
ws.schild.jave.Encoder - Input Line (5):     WMFSDKVersion   : 11.0.6002.18049
ws.schild.jave.Encoder - Input Line (6):     IsVBR           : 0
ws.schild.jave.Encoder - Input Line (7):   Duration: 00:00:04.32, start: 0.000000, bitrate: 15 kb/s
ws.schild.jave.Encoder - Input Line (8):     Stream #0:0(eng): Audio: wmavoice ([10][0][0][0] / 0x000A), 8000 Hz, mono, flt, 4 kb/s
ws.schild.jave.Encoder - Input Line (9): Stream mapping:
ws.schild.jave.Encoder - Input Line (10):   Stream #0:0 -> #0:0 (wmavoice (native) -> mp3 (libmp3lame))
ws.schild.jave.Encoder - Input Line (11): Press [q] to stop, [?] for help
ws.schild.jave.Encoder - Input Line (12): Output #0, mp3, to '<<output File location>>':
ws.schild.jave.Encoder - Input Line (13):   Metadata:
ws.schild.jave.Encoder - Input Line (14):     WMFSDKNeeded    : 0.0.0.0000
ws.schild.jave.Encoder - Input Line (15):     DeviceConformanceTemplate: S1
ws.schild.jave.Encoder - Input Line (16):     WMFSDKVersion   : 11.0.6002.18049
ws.schild.jave.Encoder - Input Line (17):     IsVBR           : 0
ws.schild.jave.Encoder - Input Line (18):     TSSE            : Lavf57.83.100
ws.schild.jave.Encoder - Input Line (19):     Stream #0:0(eng): Audio: mp3 (libmp3lame), 44100 Hz, stereo, fltp, 128 kb/s
ws.schild.jave.Encoder - Input Line (20):     Metadata:
ws.schild.jave.Encoder - Input Line (21):       encoder         : Lavc57.107.100 libmp3lame
**ws.schild.jave.Encoder - Input Line (22): [libmp3lame @ 000000000056cb20] Queue input is backward in time**
ws.schild.jave.Encoder - Input Line (23): [mp3 @ 00000000003af640] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 131849 >= 131105
ws.schild.jave.Encoder - Input Line (24): size=      70kB time=00:00:04.47 bitrate= 128.0kbits/s speed=35.9x    
ws.schild.jave.Encoder - Input Line (25): video:0kB audio:69kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.840218%

**Comment by a-schild** [comment]
@TangTing528 The new 2.4.1 relase should ignore these warnings.
In fact, the input files seem to have some error about the time line, which seems not to be unknown

https://www.google.com/search?q=ffmpeg+Queue+input+is+backward+in+time

**Comment by TangTing528** [comment]
I just tried the new code. It still throws out exceptions, but for other reasons ([libmp3lame @ 00000000004ebe00] Trying to remove 1152 samples, but the queue is empty). I'm gonna use the solution of commenting out the line 638. 

Thanks!

**Comment by a-schild** [comment]
@TangTing528 @ArunPrasathSubramani The new error message does not match the full output you posted in the above post.
Could you please also show the ouput of the above conversion?
Does the conversion finish correctly?

Your input files seem to be of questionable technical quality, how did you create them?

**Comment by ArunPrasathSubramani** [comment]
It’s a recorded voice from another system @a-child.

We don’t have much control on it.

**Comment by a-schild** [comment]
Can you try again with the 2.4.3 release?

**Comment by a-schild** [comment]
Closed as invalid, due to no answer

**Comment by ValZapod** [comment]
This is this bug in encoder: https://trac.ffmpeg.org/ticket/9755#comment:16
