### ISSUE TITLE
Some suggestions about contructor method of ws.schild.jave.MultimediaObject

### ISSUE THREAD

**Issue by JobsLeeCN** [a-schild/jave2#122]
Just like Encoder(ProcessLocator locator) method, somtimes we need point the path of FFMPEG to ours. But now, when we get start to get the video info,  we found JAVE2 always uses the ffmpeg of itself. When my server kernel is too old, we can't use the new path of FFMPEG, so that we can't get the video info we want.

**Comment by a-schild** [comment]
You should be able to implement your of FFMPEGLocator, which uses the system provided binaries or whatever you specify.
But please be aware, that some older ffmpeg executables return other output which might not work with more recent jave versions

**Comment by a-schild** [comment]
https://github.com/a-schild/jave2/blob/master/jave-core/src/main/java/ws/schild/jave/process/ffmpeg/DefaultFFMPEGLocator.java

**Comment by JobsLeeCN** [comment]
> You should be able to implement your of FFMPEGLocator, which uses the system provided binaries or whatever you specify.
> But please be aware, that some older ffmpeg executables return other output which might not work with more recent jave versions

Thank you, I'll try it.

**Comment by JobsLeeCN** [comment]
I'm so sorry for I miss the MultimediaObject(File input, ProcessLocator locator) method, this method is under the 78 lines by the decompiled code.
