### ISSUE TITLE
How can I add it in a java project instead of maven?

### ISSUE THREAD

**Issue by yasuo9x** [a-schild/jave2#123]
I have added the library in my project but cannot import into the soure code

**Comment by a-schild** [comment]
Which libraries have you added to your project?

**Comment by yasuo9x** [comment]
I added the jave2 library to my project but it doesn't have methods so I can import into the class and call them to work.

**Comment by a-schild** [comment]
Which jar files did you add to your project?
You need at least the jave core and the platform binary.

https://search.maven.org/artifact/ws.schild/jave-core/3.0.1/jar

and for example this one for linux64
https://search.maven.org/artifact/ws.schild/jave-nativebin-linux64/3.0.1/jar

**Comment by yasuo9x** [comment]
![image](https://user-images.githubusercontent.com/55038417/97383683-bb6b5500-1900-11eb-8b75-3e00bd4f86f0.png)

i can't import ws.schild to classs java project

**Comment by a-schild** [comment]
**You need to add the jave core package to your project too**

**Comment by yasuo9x** [comment]
You mean jave-1.0.2.jar library right?

**Comment by a-schild** [comment]
https://search.maven.org/artifact/ws.schild/jave-core/3.0.1/jar

**Comment by yasuo9x** [comment]
tks for support me
