### ISSUE TITLE
ws.schild.jave.EncoderException: Exit code of ffmpeg encoding run is 1

### ISSUE THREAD

**Issue by randolph555** [a-schild/jave2#128]
public static void convertM4A2PCM(String file1, String file2) {
        try {
            File source = new File(file1);
            File target = new File(file2);
            if (target.exists()) {
                target.delete();
            }
            //Audio Attributes
            AudioAttributes audio = new AudioAttributes();
            audio.setCodec("pcm_s16le");
            audio.setBitRate(16);
            audio.setChannels(1);
            audio.setSamplingRate(16000);
            //Encoding attributes
            EncodingAttributes attrs = new EncodingAttributes();
            attrs.setOutputFormat("pcm");
            attrs.setAudioAttributes(audio);
            //Encode
            Encoder encoder = new Encoder();
            encoder.encode(new MultimediaObject(source), target, attrs);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

maven :

        <dependency>
            <groupId>ws.schild</groupId>
            <artifactId>jave-all-deps</artifactId>
            <version>3.0.1</version>
        </dependency>

      <dependency>
            <groupId>ws.schild</groupId>
            <artifactId>jave-core</artifactId>
            <version>3.0.0</version>
        </dependency>

        <dependency>
            <groupId>ws.schild</groupId>
            <artifactId>jave-nativebin-osx64</artifactId>
            <version>3.0.0</version>
      </dependency>

16:47:58.628 [main] DEBUG ws.schild.jave.process.ffmpeg.DefaultFFMPEGLocator - Os name is <mac os x> isWindows: false isMac: true
16:47:58.632 [main] DEBUG ws.schild.jave.process.ffmpeg.DefaultFFMPEGLocator - Jave temp folder exists in </var/folders/hx/t5jd64cs6sd3w1fhvqqksr940000gn/T/jave>
16:47:58.633 [main] DEBUG ws.schild.jave.process.ffmpeg.DefaultFFMPEGLocator - Executable path: /var/folders/hx/t5jd64cs6sd3w1fhvqqksr940000gn/T/jave/ffmpeg-x86_64-3.0.0-osx
16:47:58.633 [main] DEBUG ws.schild.jave.process.ffmpeg.DefaultFFMPEGLocator - Executable exists in </var/folders/hx/t5jd64cs6sd3w1fhvqqksr940000gn/T/jave/ffmpeg-x86_64-3.0.0-osx>
16:47:58.643 [main] DEBUG ws.schild.jave.process.ffmpeg.DefaultFFMPEGLocator - ffmpeg executable found: /var/folders/hx/t5jd64cs6sd3w1fhvqqksr940000gn/T/jave/ffmpeg-x86_64-3.0.0-osx
16:47:58.645 [main] DEBUG ws.schild.jave.process.ffmpeg.DefaultFFMPEGLocator - Os name is <mac os x> isWindows: false isMac: true
16:47:58.645 [main] DEBUG ws.schild.jave.process.ffmpeg.DefaultFFMPEGLocator - Jave temp folder exists in </var/folders/hx/t5jd64cs6sd3w1fhvqqksr940000gn/T/jave>
16:47:58.645 [main] DEBUG ws.schild.jave.process.ffmpeg.DefaultFFMPEGLocator - Executable path: /var/folders/hx/t5jd64cs6sd3w1fhvqqksr940000gn/T/jave/ffmpeg-x86_64-3.0.0-osx
16:47:58.645 [main] DEBUG ws.schild.jave.process.ffmpeg.DefaultFFMPEGLocator - Executable exists in </var/folders/hx/t5jd64cs6sd3w1fhvqqksr940000gn/T/jave/ffmpeg-x86_64-3.0.0-osx>
16:47:58.648 [main] DEBUG ws.schild.jave.process.ffmpeg.DefaultFFMPEGLocator - ffmpeg executable found: /var/folders/hx/t5jd64cs6sd3w1fhvqqksr940000gn/T/jave/ffmpeg-x86_64-3.0.0-osx
16:47:58.678 [main] DEBUG ws.schild.jave.process.ProcessWrapper - About to execute /var/folders/hx/t5jd64cs6sd3w1fhvqqksr940000gn/T/jave/ffmpeg-x86_64-3.0.0-osx -i /tem/recognizeVoiceCaptionAudio.m4a -vn -acodec pcm_s16le -ab 16 -ac 1 -ar 16000 -f PCM -y /tem/recognizeVoiceCaptionAudio1.pcm -hide_banner
16:47:58.682 [main] DEBUG ws.schild.jave.process.ProcessWrapper - About to execute /var/folders/hx/t5jd64cs6sd3w1fhvqqksr940000gn/T/jave/ffmpeg-x86_64-3.0.0-osx -i /tem/recognizeVoiceCaptionAudio.m4a -hide_banner
16:47:58.703 [main] DEBUG ws.schild.jave.MultimediaObject - Output line: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tem/recognizeVoiceCaptionAudio.m4a':
16:47:58.704 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:   Metadata:
16:47:58.704 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:     major_brand     : M4A 
16:47:58.704 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:     minor_version   : 512
16:47:58.704 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:     compatible_brands: isomiso2
16:47:58.704 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:     encoder         : Lavf58.29.100
16:47:58.706 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:   Duration: 00:13:05.54, start: 0.000000, bitrate: 115 kb/s
16:47:58.706 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:     Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, stereo, fltp, 115 kb/s (default)
16:47:58.707 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:     Metadata:
16:47:58.707 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       handler_name    : SoundHandler
16:47:58.707 [main] DEBUG ws.schild.jave.MultimediaObject - Output line: At least one output file must be specified
16:47:58.707 [main] DEBUG ws.schild.jave.MultimediaObject - Output line: null
16:47:58.708 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (1): <Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tem/recognizeVoiceCaptionAudio.m4a':>
16:47:58.708 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (2): <  Metadata:>
16:47:58.708 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (3): <    major_brand     : M4A >
16:47:58.709 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (4): <    minor_version   : 512>
16:47:58.709 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (5): <    compatible_brands: isomiso2>
16:47:58.709 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (6): <    encoder         : Lavf58.29.100>
16:47:58.709 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (7): <  Duration: 00:13:05.54, start: 0.000000, bitrate: 115 kb/s>
16:47:58.709 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (8): <    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, stereo, fltp, 115 kb/s (default)>
16:47:58.709 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (9): <    Metadata:>
16:47:58.709 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (10): <      handler_name    : SoundHandler>
16:47:58.709 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (11): <[NULL @ 0x7f8c4c80ce00] Requested output format 'PCM' is not a suitable output format>
16:47:58.709 [main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 1 Line: 11 message: <[NULL @ 0x7f8c4c80ce00] Requested output format 'PCM' is not a suitable output format>
16:47:58.709 [main] DEBUG ws.schild.jave.ConversionOutputAnalyzer - Input Line (12): </tem/recognizeVoiceCaptionAudio1.pcm: Invalid argument>
16:47:58.709 [main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 1 Line: 12 message: </tem/recognizeVoiceCaptionAudio1.pcm: Invalid argument>
16:47:58.709 [main] ERROR ws.schild.jave.Encoder - Process exit code: 1  to recognizeVoiceCaptionAudio1.pcm
ws.schild.jave.EncoderException: Exit code of ffmpeg encoding run is 1
	at ws.schild.jave.Encoder.encode(Encoder.java:572)
	at ws.schild.jave.Encoder.encode(Encoder.java:351)
	at ws.schild.jave.Encoder.encode(Encoder.java:318)
	at com.versa.upload.service.impl.AudioFormatConversionServiceImpl.convertMP32PCM(AudioFormatConversionServiceImpl.java:163)
	at com.versa.upload.service.impl.AudioFormatConversionServiceImpl.main(AudioFormatConversionServiceImpl.java:139)

Process finished with exit code 0

how to solve this problem?

**Comment by a-schild** [comment]
**Requested output format 'PCM' is not a suitable output format**

Can you try without setting the output format to pcm?

**Comment by randolph555** [comment]
> **Requested output format 'PCM' is not a suitable output format**
> 
> Can you try without setting the output format to pcm?

I just want to get a file in pcm format

**Comment by randolph555** [comment]
> **Requested output format 'PCM' is not a suitable output format**
> 
> Can you try without setting the output format to pcm?

Is there a way to convert files in pcm format？

**Comment by mressler** [comment]
@randolph555 - Does this work when you run `ffmpeg` in command line?

**Comment by randolph555** [comment]
> @randolph555 - Does this work when you run `ffmpeg` in command line?

I can convert m4a to PCM format through ffmpeg command line, but I want to find API to achieve it

**Comment by a-schild** [comment]
What is the command line you are using?

**Comment by randolph555** [comment]
I set the format to wav, and can generate audio files with .pcm suffix, my problem has been solved, thank you。


But if the amount of concurrency is larger, the conversion efficiency will become very slow. I don’t know if there is a good solution.

**Comment by a-schild** [comment]
About performance, this depends how many cores your system has and how much concurrent conversions you fire up.
A good way to handle such thins is to use some ExecutorService and there specify how many cores/threads it's allowed to use

https://www.baeldung.com/java-executor-service-tutorial

**Comment by mressler** [comment]
@randolph555 Can you post your solution here in case someone else has the same issue?

**Comment by randolph555** [comment]
> @randolph555 Can you post your solution here in case someone else has the same issue?

Yes, of course.
