### ISSUE TITLE
I need a solution

### ISSUE THREAD

**Issue by sol545** [a-schild/jave2#137]
![image](https://user-images.githubusercontent.com/78883654/107591090-e8771580-6c1a-11eb-9f21-6ef0b4a70aa3.jpeg)![image](https://user-images.githubusercontent.com/78883654/107591093-eca33300-6c1a-11eb-9e83-8ee07a955bc8.jpeg)

**Comment by mressler** [comment]
Not sure if I can ban or report you, but I'll look into it if I get another one of these from you.
