### ISSUE TITLE
Read Me Fix

### ISSUE THREAD

**Issue by PulseBeat02** [a-schild/jave2#138]
Hello, I would figure to point out that the maven you used in the README.md relating to the jave-core artifact has the wrong version. It says it is version 3.1.0 when the latest is 3.0.1 . Perhaps you could change this to avoid further confusion. Thank you.

**Comment by PulseBeat02** [comment]
I made a PR here about it: https://github.com/a-schild/jave2/pull/139

**Comment by a-schild** [comment]
The 3.1.0 release was planned some time ago, but it did not pass all tests.
3.1.1 is no released.

**Comment by PulseBeat02** [comment]
Ah I see, sorry!
