### ISSUE TITLE
convert mkv to mp4 fail

### ISSUE THREAD

**Issue by calm04061** [a-schild/jave2#14]
<dependency>
            <groupId>ws.schild</groupId>
            <artifactId>jave-core</artifactId>
            <version>2.4.1</version>
        </dependency>
        <dependency>
            <groupId>ws.schild</groupId>
            <artifactId>jave-native-win64</artifactId>
            <version>2.4.1</version>
        </dependency>

13:48:11.472 [main] DEBUG ws.schild.jave.FFMPEGExecutor - Executable path: C:\Users\ding\AppData\Local\Temp\jave\ffmpeg-amd64-2.4.1.exe
13:48:11.472 [main] DEBUG ws.schild.jave.FFMPEGExecutor - ffmpeg executable found: C:\Users\ding\AppData\Local\Temp\jave\ffmpeg-amd64-2.4.1.exe
13:48:11.472 [main] DEBUG ws.schild.jave.FFMPEGExecutor - About to execute C:\Users\ding\AppData\Local\Temp\jave\ffmpeg-amd64-2.4.1.exe -i K:\ceshi\1.mkv -vcodec copy -acodec copy -y K:\ceshi\test.mp4 -hide_banner 
13:48:14.059 [main] DEBUG ws.schild.jave.FFMPEGExecutor - About to execute C:\Users\ding\AppData\Local\Temp\jave\ffmpeg-amd64-2.4.1.exe -i K:\ceshi\1.mkv -hide_banner 
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line: Input #0, matroska,webm, from 'K:\ceshi\1.mkv':
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:   Metadata:
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:     encoder         : libebml v1.3.4 + libmatroska v1.4.5
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:     creation_time   : 2018-06-19T12:16:12.000000Z
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:   Duration: 02:19:55.70, start: 0.000000, bitrate: 1816 kb/s
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:     Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:     Metadata:
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       BPS             : 1686071
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       BPS-eng         : 1686071
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       DURATION        : 02:19:55.637000000
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       DURATION-eng    : 02:19:55.637000000
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       NUMBER_OF_FRAMES: 201294
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       NUMBER_OF_FRAMES-eng: 201294
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       NUMBER_OF_BYTES : 1769455275
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       NUMBER_OF_BYTES-eng: 1769455275
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       _STATISTICS_WRITING_APP: mkvmerge v10.0.0 ('To Drown In You') 32bit
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       _STATISTICS_WRITING_APP-eng: mkvmerge v10.0.0 ('To Drown In You') 32bit
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       _STATISTICS_WRITING_DATE_UTC: 2018-06-19 12:16:12
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       _STATISTICS_WRITING_DATE_UTC-eng: 2018-06-19 12:16:12
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:     Stream #0:1(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:     Metadata:
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       BPS             : 127989
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       BPS-eng         : 127989
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       DURATION        : 02:19:55.691000000
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       DURATION-eng    : 02:19:55.691000000
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       NUMBER_OF_FRAMES: 393548
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       NUMBER_OF_FRAMES-eng: 393548
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       NUMBER_OF_BYTES : 134319826
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       NUMBER_OF_BYTES-eng: 134319826
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       _STATISTICS_WRITING_APP: mkvmerge v10.0.0 ('To Drown In You') 32bit
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       _STATISTICS_WRITING_APP-eng: mkvmerge v10.0.0 ('To Drown In You') 32bit
13:48:14.122 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       _STATISTICS_WRITING_DATE_UTC: 2018-06-19 12:16:12
13:48:14.137 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       _STATISTICS_WRITING_DATE_UTC-eng: 2018-06-19 12:16:12
13:48:14.137 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
13:48:14.137 [main] DEBUG ws.schild.jave.MultimediaObject - Output line:       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
13:48:14.137 [main] DEBUG ws.schild.jave.MultimediaObject - Output line: At least one output file must be specified
13:48:14.137 [main] DEBUG ws.schild.jave.MultimediaObject - Output line: null
13:48:14.570 [main] DEBUG ws.schild.jave.Encoder - Input Line (1): Input #0, matroska,webm, from 'K:\ceshi\1.mkv':
13:48:14.989 [main] DEBUG ws.schild.jave.Encoder - Input Line (2):   Metadata:
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (3):     encoder         : libebml v1.3.4 + libmatroska v1.4.5
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (4):     creation_time   : 2018-06-19T12:16:12.000000Z
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (5):   Duration: 02:19:55.70, start: 0.000000, bitrate: 1816 kb/s
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (6):     Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (7):     Metadata:
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (8):       BPS             : 1686071
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (9):       BPS-eng         : 1686071
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (10):       DURATION        : 02:19:55.637000000
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (11):       DURATION-eng    : 02:19:55.637000000
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (12):       NUMBER_OF_FRAMES: 201294
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (13):       NUMBER_OF_FRAMES-eng: 201294
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (14):       NUMBER_OF_BYTES : 1769455275
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (15):       NUMBER_OF_BYTES-eng: 1769455275
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (16):       _STATISTICS_WRITING_APP: mkvmerge v10.0.0 ('To Drown In You') 32bit
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (17):       _STATISTICS_WRITING_APP-eng: mkvmerge v10.0.0 ('To Drown In You') 32bit
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (18):       _STATISTICS_WRITING_DATE_UTC: 2018-06-19 12:16:12
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (19):       _STATISTICS_WRITING_DATE_UTC-eng: 2018-06-19 12:16:12
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (20):       _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (21):       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (22):     Stream #0:1(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (23):     Metadata:
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (24):       BPS             : 127989
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (25):       BPS-eng         : 127989
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (26):       DURATION        : 02:19:55.691000000
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (27):       DURATION-eng    : 02:19:55.691000000
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (28):       NUMBER_OF_FRAMES: 393548
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (29):       NUMBER_OF_FRAMES-eng: 393548
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (30):       NUMBER_OF_BYTES : 134319826
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (31):       NUMBER_OF_BYTES-eng: 134319826
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (32):       _STATISTICS_WRITING_APP: mkvmerge v10.0.0 ('To Drown In You') 32bit
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (33):       _STATISTICS_WRITING_APP-eng: mkvmerge v10.0.0 ('To Drown In You') 32bit
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (34):       _STATISTICS_WRITING_DATE_UTC: 2018-06-19 12:16:12
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (35):       _STATISTICS_WRITING_DATE_UTC-eng: 2018-06-19 12:16:12
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (36):       _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
13:48:15.512 [main] DEBUG ws.schild.jave.Encoder - Input Line (37):       _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Disconnected from the target VM, address: '127.0.0.1:59224', transport: 'socket'
13:48:15.528 [main] DEBUG ws.schild.jave.Encoder - Input Line (38): Output #0, mp4, to 'K:\ceshi\test.mp4':
ws.schild.jave.EncoderException: Output #0, mp4, to 'K:\ceshi\test.mp4':
	at ws.schild.jave.Encoder.encode(Encoder.java:601)

**Comment by calm04061** [comment]
public static void main(String[] args) {
        MultimediaObject multimediaObject = new MultimediaObject(new File("K:/ceshi", "1.mkv"));
        try {
            Encoder encoder = new Encoder();
            EncodingAttributes attributes = new EncodingAttributes();
            AudioAttributes audioAttributes = new AudioAttributes();
            audioAttributes.setCodec(AudioAttributes.DIRECT_STREAM_COPY);
            attributes.setAudioAttributes(audioAttributes);
            VideoAttributes videoAttributes = new VideoAttributes();
            videoAttributes.setCodec(VideoAttributes.DIRECT_STREAM_COPY);
            attributes.setVideoAttributes(videoAttributes);
            encoder.encode(multimediaObject, new File("K:\\ceshi", "3.mp4"), attributes, new EncoderProgressListener() {

                @Override
                public void sourceInfo(MultimediaInfo info) {

                }

                @Override
                public void progress(int permil) {
                    System.out.println(permil);
                }

                @Override
                public void message(String message) {
                    System.out.println(message);
                }
            });
        } catch (EncoderException e) {
            e.printStackTrace();
        }
    }

**Comment by a-schild** [comment]
@calm04061 Could you please post the output of the conversion including all leading blanks? (They are important for the output parsing)

**Comment by a-schild** [comment]
I made some code changes to handle the copy stream option correctly.
Can you please try with the 2.4.2-SNAPSHOT release?
If it still fails, please post the full output **including all leading spaces.**

**Comment by calm04061** [comment]
使用2.4.2-SNAPSHOT版本转换成功了，非常感谢

**Comment by a-schild** [comment]
So it is working with the new version?
If yes, please close the issue. (And please answer in english if possible)

**Comment by calm04061** [comment]
@a-schild Yes ,it is working with the new version. 
Thanks very much!
