### ISSUE TITLE
missing artifact issue

### ISSUE THREAD

**Issue by dream-djaxtech** [a-schild/jave2#143]
importing below dependency causing missing artifact issue 

`<dependency>
			<groupId>ws.schild</groupId>
			<artifactId>jave-core</artifactId>
			<version>3.1.0</version>
		</dependency>
`

**Comment by peterkronenberg** [comment]
It is version 3.0.1, not 3.1.0

**Comment by a-schild** [comment]
The 3.1.0 release was planned some time ago, but it did not pass all tests.
3.1.1 is no released.

**Comment by peterkronenberg** [comment]
How long will it take for 3.1.1 to be available on Maven?

**Comment by a-schild** [comment]
Is now published and should be visible in maven in ~10 minuten, in mavencentral search in 2-3 hours
