### ISSUE TITLE
How do I convert an GIF into a MP4 Video in Jave2?

### ISSUE THREAD

**Issue by PulseBeat02** [a-schild/jave2#146]
According to [this](https://unix.stackexchange.com/questions/40638/how-to-do-i-convert-an-animated-gif-to-an-mp4-or-mv4-on-the-command-line) post about the correct arguments to use, it says that the proper command to perform the conversion is as follows (where `animated.gif` is your gif file and `video.mp4` is the video file):

```
ffmpeg -i animated.gif -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" video.mp4
```

I tried to convert this in Java by using this piece of code (where image is the gif file and output is the video file).

```java
    final AudioAttributes audio = new AudioAttributes();
    audio.setVolume(0);
    final EncodingAttributes attrs = new EncodingAttributes();
    attrs.setInputFormat("gif");
    attrs.setOutputFormat("mp4");
    attrs.setAudioAttributes(audio);
    final File output =
        new File(parentFolder, FilenameUtils.getBaseName(name) + ".mp4");
    try {
      encoder.encode(new MultimediaObject(image), output, attrs);
    } catch (final EncoderException e) {
      e.printStackTrace();
    }
 ```
 
 Unfortunately, this doesn't properly work. Do you know perhaps the correct way to perform this conversion?

**Comment by a-schild** [comment]
What do you mean by "this doesn't properly work."?

No need to specify input format
For me this works when using VLC player for playback, in other video players it depends on the width+height of the input file, if it's not divisble by 2 then for example the windows media player doesn't show anything (Not even an error)

```
    final EncodingAttributes attrs = new EncodingAttributes();
    final VideoAttributes vAttrs= new VideoAttributes();
    attrs.setVideoAttributes(vAttrs);
    attrs.setOutputFormat("mp4");
    final File output =
        new File("F:\\x\\gif.mp4");
    try {
        Encoder encoder = new Encoder();
      encoder.encode(new MultimediaObject(new File("F:\\x\\giphy.gif")), output, attrs);
    } catch (final EncoderException e) {
      e.printStackTrace();
```

For a more compatible way to generate the video, specify the pixel format and do a appropriate scaling:

```
    final EncodingAttributes attrs = new EncodingAttributes();
    final AudioAttributes audio = new AudioAttributes();
    audio.setVolume(0);
    attrs.setAudioAttributes(audio);
    final VideoAttributes vAttrs= new VideoAttributes();
    vAttrs.setPixelFormat("yuv420p");
    attrs.setVideoAttributes(vAttrs);
    attrs.setOutputFormat("mp4");
    vAttrs.addFilter(new ScaleFilter(VideoSize.vga, ForceOriginalAspectRatio.DISABLE));
    final File output =
        new File("F:\\x\\gif.mp4");
    try {
        Encoder encoder = new Encoder();
      encoder.encode(new MultimediaObject(new File("F:\\x\\giphy.gif")), output, attrs);
    } catch (final EncoderException e) {
      e.printStackTrace();
    }
```

**Comment by a-schild** [comment]
In the newest 3.2.0-SNAPSHOT relase you can now specify a string expression for the scaling filter.

`    vidAttr.addFilter(new ScaleFilter("trunc(iw/2)*2:trunc(ih/2)*2"));`

**Comment by PulseBeat02** [comment]
I see. Thank you for the help!
