### ISSUE TITLE
Can add a custom command line usage?

### ISSUE THREAD

**Issue by LanguidMe** [a-schild/jave2#147]
I now have a video conversion m3u8 requirement, and I want the actuator to directly execute the command line I spliced，Whether it can be or not?(My English is not good. The above is translated. Please forgive me if there is anything bad)

**Comment by a-schild** [comment]
I think in that case it would be simpler if you just start the ffmpeg executable as a process from java, without the help of jave.

Or what would the command line look like?

**Comment by LanguidMe** [comment]
`ffmpeg -i D:\videos\BgFCWkn00qPBmWVzIEf0eQjaekx0oRjlk9VY2PcR.mp4 -c:v libx264 -hls_time 60 -hls_list_size 0 -c:a aac -strict -2 -f hls D:\videos\03%d.m3u8` This is my command line. I want to use Jave to impl.I can also use java to execute ffmpeg. Because I have been using Jave, I want to consult. Will there be a custom encoder in the future?It doesn't matter if there is no custom encoder.thank

**Comment by a-schild** [comment]
Somthing like this should work:

```
locator = new DefaultFFMPEGLocator();
ProcessWrapper localFFMPEG = locator.createExecutor();
localFFMPEG.addArgument("-argument1");
localFFMPEG.addArgument("-argument2");
try {
      localFFMPEG.execute();
}
.
.

```

**Comment by LanguidMe** [comment]
I'll give it a try.thank

**Comment by shengtu0328** [comment]
> Somthing like this should work:
> 
> ```
> locator = new DefaultFFMPEGLocator();
> ProcessWrapper localFFMPEG = locator.createExecutor();
> localFFMPEG.addArgument("-argument1");
> localFFMPEG.addArgument("-argument2");
> try {
>       localFFMPEG.execute();
> }
> .
> .
> ```

I used this code,but it doesnt work.

    ```
    String s = "-i /Users/videopls/develop/ffmpeg/input.avi /Users/videopls/develop/ffmpeg/output/output.mp4";

        DefaultFFMPEGLocator locator = new DefaultFFMPEGLocator();
        ProcessWrapper localFFMPEG = locator.createExecutor();
        localFFMPEG.addArgument(s);
        try {
            localFFMPEG.execute();
        }catch (Exception e){
            e.printStackTrace();
        }
```

this is ouput, but "output.mp4"is not existed.

```

18:19:28.900 [main] DEBUG ws.schild.jave.process.ffmpeg.DefaultFFMPEGLocator - Os name is <mac os x> isWindows: false isMac: true
18:19:28.907 [main] DEBUG ws.schild.jave.process.ffmpeg.DefaultFFMPEGLocator - Jave temp folder exists in </var/folders/fp/fg__cpln099g08625c1vf0xm0000gn/T/jave>
18:19:28.908 [main] DEBUG ws.schild.jave.process.ffmpeg.DefaultFFMPEGLocator - Executable path: /var/folders/fp/fg__cpln099g08625c1vf0xm0000gn/T/jave/ffmpeg-x86_64-3.2.0-osx
18:19:28.908 [main] DEBUG ws.schild.jave.process.ffmpeg.DefaultFFMPEGLocator - Executable exists in </var/folders/fp/fg__cpln099g08625c1vf0xm0000gn/T/jave/ffmpeg-x86_64-3.2.0-osx>
18:19:28.993 [main] DEBUG ws.schild.jave.process.ffmpeg.DefaultFFMPEGLocator - ffmpeg executable found: /var/folders/fp/fg__cpln099g08625c1vf0xm0000gn/T/jave/ffmpeg-x86_64-3.2.0-osx
18:19:29.010 [main] DEBUG ws.schild.jave.process.ProcessWrapper - About to execute /var/folders/fp/fg__cpln099g08625c1vf0xm0000gn/T/jave/ffmpeg-x86_64-3.2.0-osx -i /Users/videopls/develop/ffmpeg/input.avi /Users/videopls/develop/ffmpeg/output/output.mp4 -hide_banner
```

**Comment by a-schild** [comment]
@shengtu0328 See #220
