### ISSUE TITLE
I get an error in Android SDK 30.

### ISSUE THREAD

**Issue by yyms3275** [a-schild/jave2#152]
error code :
java.io.IOException: Cannot run program "/data/user/0/"MYAPP"/cache/jave/ffmpeg-aarch64-3.1.1": error=13, Permission denied

Is there no workaround?

compileSdkVersion 30
buildToolsVersion "30.0.3"
minSdkVersion 21
targetSdkVersion 30

**Comment by a-schild** [comment]
I don't know Anrdoid well enough to answer your question.
It could be that the executable is not correctly flagged as executable (permissionwise) or then the location is not allowing starting executables...

**Comment by a-schild** [comment]
Closed due to missing feedback
