### ISSUE TITLE
How would you add support for other operating systems?

### ISSUE THREAD

**Issue by PulseBeat02** [a-schild/jave2#153]
I am a bit confused on where you managed to get the full binaries for the x32 and x64 versions of Windows, Mac, and Linux. When I go onto the FFmpeg site and look at the site for prebuilt binaries, I usually instead get a folder that contains ffmpeg, ffmprobe, etc, instead of just one file.

If I wanted to support amd64, how would I go about creating such a binary to support these users? I can't find this in the Jave manual.

**Comment by PulseBeat02** [comment]
Actually nevermind. Further resarch helped me do this.

**Comment by a-schild** [comment]
What OS/Architecture did you add?
Care to provide it to the community?

**Comment by PulseBeat02** [comment]
It turns out that the provided binaries already supported the operating system I was looking for. Sorry about this.
