### ISSUE TITLE
java-core is not download

### ISSUE THREAD

**Issue by memoryoverflow** [a-schild/jave2#159]
<dependency>
    <groupId>ws.schild</groupId>
    <artifactId>jave-core</artifactId>
    <version>3.1.1</version>
</dependency>

this is not download.

**Comment by naffan2014** [comment]
我可以

**Comment by a-schild** [comment]
@memoryoverflow It's in maven central.
Either use maven for this of download it from there manually.

https://mvnrepository.com/artifact/ws.schild/jave-core/3.1.1
