### ISSUE TITLE
So how to upgrade ffmpeg used in jave2 to v4.4

### ISSUE THREAD

**Issue by aiyaya666** [a-schild/jave2#161]
The following error occurred while converting a network FLV stream to mp4.
`Overread VUI by 5 bits>
SPS decoding failure, trying again after escaping the NAL>
Overread VUI by 8 bits>
sps_id 0 out of range>
SPS decoding failure, trying again after escaping the NAL>
sps_id 0 out of range>
non-existing PPS 0 referenced>
Overread VUI by 5 bits>`
This problem does not occur when using ffmpeg v4.4.
So how to upgrade ffmpeg used in jave2 to v4.4

**Comment by a-schild** [comment]
You could prove a pull request with the new versions, this would help all users.
It's on my todo list, but so far not high priority...

The other thing would be to implement your own ffmpeg locator class, which provides the new binaries for the platform you need.
