### ISSUE TITLE
Cannot resolve ws.schild:jave-nativebin-linux-arm64:3.2.0

### ISSUE THREAD

**Issue by JJ-Jiajia** [a-schild/jave2#168]
I'm using JAVE2 3.2 from maven,but when i build my project,there is an error occur:

Could not resolve dependencies for project com.apus:monet:jar:0.0.1-SNAPSHOT: Could not find artifact ws.schild:jave-nativebin-linux-arm64:jar:3.2.0

is there sth i went wrong?

**Comment by a-schild** [comment]
There was a problem with uploading the arm64 binary to maven central.

The win32 build was also missing, but they are now both uploaded.
It might take a few hours until they are available all over the world,
