### ISSUE TITLE
I get an error when encode PCM files

### ISSUE THREAD

**Issue by gg381534551** [a-schild/jave2#174]
I get an error when encode PCM files, but other audio formats such as MP3, WAV are fine。

It is good to execute the following command

ffmpeg-x86_64-3.2.0-osx -acodec pcm_s16le -ac 1 -ar 8000 -f s16le -i test.pcm  -vn -acodec pcm_s16le -ac 1 -ar 16000 -f s8 -y  result.pcm -hide_banner   

Executing this command returns an error

ffmpeg-x86_64-3.2.0-osx -i test.pcm -hide_banner

ws.schild.jave.InputFormatException: Invalid data found when processing input

**Comment by a-schild** [comment]
Could you please attach a test file which causes the problem?
And please turn logging on, so we see what ffmpeg has to say
