### ISSUE TITLE
.ogg -> .mp3 throws exception, but seems to complete anyway

### ISSUE THREAD

**Issue by stefan-reich** [a-schild/jave2#19]
I'm using your latest release. Conversion code:

```
  new AudioAttributes audio;
  audio.setCodec("libmp3lame");
  new EncodingAttributes attrs;
  attrs.setFormat("mp3");
  attrs.setAudioAttributes(audio);
  new Encoder().encode(new MultimediaObject(ogg), mp3, attrs);
```

Audio file: [buggy.ogg](http://butter.botcompany.de:8080/1015408/raw/1400127/buggy.ogg)

Error: 

```
Converting /root/JavaX-Data/Stored Voice Messages/66383863-1535117667872.ogg to /root/JavaX-Data/Stored Voice Messages/66383863-1535117667872.mp3
ws.schild.jave.EncoderException: In step: 3 Error in line 14 : <[ogg @ 0x4fd9c80] Packet processing failed: Invalid data found when processing input>
	at ws.schild.jave.ConversionOutputAnalyzer.analyzeNewLine(ConversionOutputAnalyzer.java:155)
	at ws.schild.jave.Encoder.encode(Encoder.java:530)
	at ws.schild.jave.Encoder.encode(Encoder.java:340)
	at main.oggToMP3(m1017517.java:339)
	at main$2$1$1.run(m1017517.java:117)

```

Platform is Linux 64. ffmpeg seems to handle the same file fine.

**Comment by a-schild** [comment]
The input stream is buggy, so ffmpeg throws a lot of warning/errors, but still seems to be able to complete the conversion.

I reworked the parsing code, so it is more robust for such buggy inputs.

Can you please test with the 2.4.3-SNAPSHOP release?

**Comment by stefan-reich** [comment]
Wow thanks. so in effect Telegram gives out broken .oggs! I copied the file
verbatim.

André Schild <notifications@github.com> schrieb am Fr., 24. Aug. 2018 18:52:

**Comment by a-schild** [comment]
Unfortunally we see lots of incomplete/broken audio and video files out in the wild, generated by many different softwares.

Can ypu please check if the snapshot version works for you and then close the issue?

**Comment by stefan-reich** [comment]
Yes, it works fine, thank you!

```
Converting /home/stefan/Audio/buggy.ogg to /tmp/buggy.mp3
  [done]
```

Check out [how my bot is using your software](http://t.me/Hello_Computer) if you're bored... :smiley:
