### ISSUE TITLE
Can you make it a Maven Project ?

### ISSUE THREAD

**Issue by goxr3plus** [a-schild/jave2#2]
There is no way to get JAVE with Maven anywhere ... trying to create a repository for it in order to get with Maven ....

https://github.com/goxr3plus/JAVE

Can you make this repository a Maven Project so it is more easy for the community please :) Love you too .

**Comment by a-schild** [comment]
Yep, will do it, but give me 1-2 weeks

**Comment by goxr3plus** [comment]
Something more i would like to discuss. Can we make it produce a jar which will contain ffmpeg for all 3 major desktop platforms ( Windowd, Linux, Mac) so it creates except of different jars, a fat one also.

Like actually the original JAVE  jar which supports both Linux and Windows 32 bits at once in one jar.

**Comment by a-schild** [comment]
Yes,

I think a core + platform jars, and a fat one. 
All individual dependencies

**Comment by a-schild** [comment]
Can you try the latest trunk version?
You will need to download the repository and do a full build so it installs the maven artifacts locally.
Then in your project, add jave-core in version 2.1.0-SNAPSHOT as a dependency and also the correct native version you require. 
You can also add all native dependencies, win+linux should work, OS-X not yet

It's completely untested for the moment

**Comment by goxr3plus** [comment]
I forked your project yesterday and made very big changes to it. Now it
supports Java 8 and above, I transformed it on a Maven project, updated
read me etc.

Have a look :)

https://github.com/goxr3plus/jave2

Currently it supports only Windows amd64.

I am trying to use the latest 4.0 FFMPEG.exe but when i replace the one you
had before the program is not anymore running.


Also one more problem, the ProgressListener is not working at all on
Jave2...

**Comment by a-schild** [comment]
I have a current version with ffmpeg 3.4.2 which works fine now
Also I included some first unit tests but there is a lot more which can be done.

Do you think we can already move on to ffmpeg 4.0?

**Comment by goxr3plus** [comment]
I love that you passed the project on Maven, i will fork it again i changed
the code to not have the old depenfency in that logger from 2007.

How many new features FFMPEG4 includes?

**Comment by a-schild** [comment]
Make a pull request with the new logger, I will include it

**Comment by a-schild** [comment]
What do you think, should I look to put the project in maven central?
For this, I would however need to move the classes in a name space owned by me or my company.

The package names would then been like:
ws.schild.jave
or
org.aarboard.jave

**Comment by goxr3plus** [comment]
You can make releases on Github . But it's completely okay if you put your
name for Maven. With Github releases we can use Jitpack.io and grab them
easily with Maven, Gradle etc. As you wish :)

**Comment by goxr3plus** [comment]
I will make a pull request very soon.

**Comment by goxr3plus** [comment]
Please drop a release for the latest Maven 2.3.0 version so i can use it with JitPack.io / https://jitpack.io/#a-schild/jave2

**Comment by goxr3plus** [comment]
ws.schild.jave is a good one :)
