### ISSUE TITLE
"Process hasn't exited"

### ISSUE THREAD

**Issue by stefan-reich** [a-schild/jave2#20]
Anything to worry about? File is converted fine...

```
Converting /root/JavaX-Data/Stored Voice Messages/604039341-1535322635081.ogg to /root/JavaX-Data/Stored Voice Messages/604039341-1535322635081.mp3
java.lang.IllegalThreadStateException: process hasn't exited
	at java.base/java.lang.ProcessImpl.exitValue(ProcessImpl.java:521)
	at ws.schild.jave.FFMPEGExecutor.getProcessExitCode(FFMPEGExecutor.java:209)
	at ws.schild.jave.Encoder.encode(Encoder.java:553)
	at ws.schild.jave.Encoder.encode(Encoder.java:349)

```

**Comment by a-schild** [comment]
Strange, but no need to worry.
What platform are you running it on, and how many cores/cpu's are active on that system?

Looks like a race condition in the shutdown code

**Comment by stefan-reich** [comment]
It's a 4 core virtual Linux (64 bit) with JDK 10 (Oracle).

Thanks for your answer

**Comment by caolj** [comment]
I tried to use 2.4.3 and 2.4.2.
2.4.2 do not has the problem "Process hasn't exited"

**Comment by efendizadeh** [comment]
Same problem with 2.4.3

java.lang.IllegalThreadStateException: process hasn't exited
	at java.lang.UNIXProcess.exitValue(Unknown Source)
	at ws.schild.jave.FFMPEGExecutor.getProcessExitCode(FFMPEGExecutor.java:209)
	at ws.schild.jave.Encoder.encode(Encoder.java:553)
	at ws.schild.jave.Encoder.encode(Encoder.java:349)
......

**Comment by a-schild** [comment]
Can you please test with the 2.4.4-SNAPSHOT  ?
It has some code to wait for process termination added

**Comment by efendizadeh** [comment]
Fixed 👍 

Could you please confirm, is Encoder thread safe?

Maven central latest version for jave-all-deps is 2.4.2 https://mvnrepository.com/artifact/ws.schild/jave-all-deps

P.S. When you are planing publish 2.4.4 to Maven?

**Comment by a-schild** [comment]
Yes, it should be thread safe, if you find some race conditions, then we will look into it and fix them.
2.4.4 is now just published
The all-deps was missing in the deploy for 2.4.3, it's now also available
