### ISSUE TITLE
Update to latest ffmpeg win32 6.0 version

### ISSUE THREAD

**Issue by goxr3plus** [a-schild/jave2#223]
Looks like we should update to latest version 6.0 for ffmpeg for windows now we have version 4.4.1  

https://git.ffmpeg.org/ffmpeg.git

![image](https://user-images.githubusercontent.com/20374208/221720273-edd3401b-0825-4716-9dab-141d81e52e8b.png)

Library is getting very popular 💯 🥇 

@a-schild

**Comment by a-schild** [comment]
@goxr3plus Do you know of a place to find the 6.0 win32 binaries?

**Comment by a-schild** [comment]
Support for win32 will be dropped in the next release.
