### ISSUE TITLE
Silk cannot be converted

### ISSUE THREAD

**Issue by bingluchen** [a-schild/jave2#230]
An error occurred when I converted silk " Invalid data found when processing input".
What shall I do?

**Comment by a-schild** [comment]
Is that only with a specific media file, or does it happen with all files?
What are your conversion parameters?

**Comment by bingluchen** [comment]
A specific media file.
File source = new File("input.silk");
            File target = new File("out.mp3");
            //Audio Attributes
            AudioAttributes audio = new AudioAttributes();
            audio.setCodec("libmp3lame");
            audio.setBitRate(128000);
            audio.setChannels(2);
            audio.setSamplingRate(44100);
            EncodingAttributes attrs = new EncodingAttributes();
            attrs.setOutputFormat("mp3");
            attrs.setAudioAttributes(audio);
            Encoder encoder = new Encoder();
            encoder.encode(new MultimediaObject(source), target, attrs);
