### ISSUE TITLE
How to use jave-native-linux64.jar

### ISSUE THREAD

**Issue by caolj** [a-schild/jave2#24]
I always put ffmpeg to java.io.tmp folder,but i cannot use this jar.
can you help me to show how to use it?thanks

**Comment by a-schild** [comment]
You don't need to to put your own ffmpeg version in a folder.
The jave.native-linux64.jar includes the native ffmpeg for the amd64 architecture.

If it does not work, please show your code and what error happens

**Comment by caolj** [comment]
thanks for answer.this is the problem
> 09:37:19.160 [main] DEBUG ws.schild.jave.FFMPEGExecutor - Executable path: C:\Users\caolj\AppData\Local\Temp\jave\ffmpeg-x86-2.4.2.exe
Exception in thread "main" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.nio.file.Files.copy(Files.java:2984)
	at ws.schild.jave.DefaultFFMPEGLocator.copy(DefaultFFMPEGLocator.java:124)
	at ws.schild.jave.DefaultFFMPEGLocator.copyFile(DefaultFFMPEGLocator.java:109)
	at ws.schild.jave.DefaultFFMPEGLocator.<init>(DefaultFFMPEGLocator.java:73)
	at ws.schild.jave.Encoder.<init>(Encoder.java:71)
	at com.caolj.speech.Sample2.main(Sample2.java:25)

Process finished with exit code 1
---------------------------------------

Both Win10 And CentOS happens this problem,Now I have to put ffmpeg to java.io.tmpdir

**Comment by a-schild** [comment]
The ffmpeg-x86-2.4.2.exe is the 32-bit windows version of the binaries, which isn't included in the linux64 jar file.
If you wish to target all platforms, you can include the `jave-all-deps`library which provides all available binaries (win 32+64, linux intel 32+amd 64 and OS-X)

**Comment by a-schild** [comment]
The stack trace shows, that it is looking for the 32-bit ffmpeg but not finding it.
Are you including the 64bit win jar, but running a 32bit jvm?

If not, what jvm are you running? (Version and bitcount)

**Comment by a-schild** [comment]
The 2.4.4-SNAPSHOT has some more info messages when the architektures do not match

**Comment by goxr3plus** [comment]
@caolj Is your problem solved :)?

**Comment by a-schild** [comment]
No feedback from user
