### ISSUE TITLE
Command execution vulnerability

### ISSUE THREAD

**Issue by Dollhouse-18** [a-schild/jave2#246]
Execute arbitrary commands by controlling ffmpegExecutablePath and processWrapper.addArgument

`package org.example.rasp;

import ws.schild.jave.process.ProcessWrapper;
import java.io.*;
public class FFmpegExample {
    public static void main(String[] args) throws IOException {

        String ffmpegExecutablePath = "curl";
        String inputFilePath = "/Users/D0L1/test/1.mp4";
        String outputFilePath = "/Users/D0L1/test/2.mp4";

        ProcessWrapper processWrapper = new ProcessWrapper(ffmpegExecutablePath);
        processWrapper.addArgument("127.0.0.1:9999/test");
        processWrapper.addArgument(inputFilePath);
        processWrapper.addArgument("-c:v");
        processWrapper.addArgument("copy");
        processWrapper.addArgument("-c:a");
        processWrapper.addArgument("aac");
        processWrapper.addArgument(outputFilePath);
        System.out.println(processWrapper);

        InputStream errorStream = null;
        try {
            processWrapper.execute();

            Thread.sleep(10000);
         
            InputStream inputStream = processWrapper.getInputStream();
            OutputStream outputStream = processWrapper.getOutputStream();
            errorStream = processWrapper.getErrorStream();

        
            System.out.println(inputStream);
            System.out.println(outputStream);
            processWrapper.close();

  
        } catch (Exception e) {
            e.printStackTrace();
            BufferedReader errorReader = new BufferedReader(new InputStreamReader(errorStream));
            String line;
            while ((line = errorReader.readLine()) != null) {
                System.err.println(line);
            }

        }
    }
}
`

**Comment by a-schild** [comment]
Hello,

not sure you know what this is.
Of course you can execute other executables if you provide your own ffmpeglocater class.
That's the reason of existence of this class, that you can provide your own executable version of ffmpeg.

It's just like you file a vulnerability on bash to be able to execute other things...

**Comment by Dollhouse-18** [comment]
You should add a method to determine whether the incoming ffmpeg is correct, rather than other unexpected commands. You can use a whitelist to restrict incoming file names containing ffmpeg or add a blacklist to prohibit the execution of high-risk commands, such as reboot.

**Comment by a-schild** [comment]
How do we detect if it's correct?
A file name based black/white list won't help, as you can copy/rename executables as you wish

**Comment by Dollhouse-18** [comment]
private static boolean isPathSafe(String path) {
     
        if (!path.endsWith("ffmpeg")) {
            return false;
        }

      
        if (path.contains("reboot") || path.contains("rm") || path.contains("shutdown")) {
            return false;
        }

      
        return true;
    }

**Comment by Dollhouse-18** [comment]
I only think of this way

**Comment by Dollhouse-18** [comment]
I don't have a particularly good way, this is a simple demo

**Comment by a-schild** [comment]
All the root commands should anyway not be accessible to the application.
You should not run applications as root user.

If you have a correctly restricted account, then there would be no reboot/format/mkfs etc. possible from your java application.
And the java application needs to be modified to execute other executables, and this is a use case we have if someone want's to use other binaries than the ones delived via the jar files.

**Comment by Dollhouse-18** [comment]
yes All the root commands should anyway not be accessible to the application.

Commands like reboot are just examples. More often attackers will use curl to download webshells and viruses.
