### ISSUE TITLE
Copying media info from source to target

### ISSUE THREAD

**Issue by dorzhinov** [a-schild/jave2#25]
When I convert audio, e.g. from flac to mp3, how can I copy media info like artist, album, year, track # and genre from a source to the target?

**Comment by a-schild** [comment]
If the default does not copy it over, then you can try with the new 2.4.4-SNAPSHOT version and settings the setMapMetaData(true) flas in the encoding attributes.
If this does not help, please post a sample file along with your code

**Comment by a-schild** [comment]
No feedback from user
