### ISSUE TITLE
FXConverter application based on Jave2

### ISSUE THREAD

**Issue by goxr3plus** [a-schild/jave2#26]
HELLOOOO :) 

I will start making a converter based on Jave2 fully , for UI i will use JavaFX and the repository is here https://github.com/goxr3plus/XR3Converter

I want to add you as a collaborator . Currently thinking to implement the UI etc.

Main functionality :+1: 

1) Convert any audio to any audio
2) Convert any video to any video
3) Extract audio from any video

What you think ? You like the idea :) ? I don't know how to make the ui in terms of many settings for converting any audio to any audio the user must be able to modify any parameters :) 

Let me know your opinion on how to design it . Believe me it will be one of the best out there once we start it :)

**Comment by a-schild** [comment]
Hello,

i will gladly help with the jave part of the project, but not on a UI as you intend to do it.
I already have enough open source projects I'm working on, and UI isn't what interests me most

**Comment by goxr3plus** [comment]
Of course i will work all the UI :) .

The problem for me is that i don't know for example let's say the user wants to convert wav to mp3 ...
what are all the available settings and options that she/he can set ? Or another example mp3 to ogg what are all the available settings.

I mean for me it is easy to implement all the UI  , i  just need to know how to present all that bunch of settings user can set and what settings user can set with Jave 2....

I will have a demo very soon for you to see and reccomend :) 

Very very happy that you exist and support this amazing library :)

**Comment by goxr3plus** [comment]
Should we make some ready classes with predefined settings to make the life of programmer easier ? 

For example [TarsosTrancoder ] (https://github.com/JorenSix/TarsosTranscoder/blob/master/src/be/tarsos/transcoder/DefaultAttributes.java)has this class (should i make a bunch of those ? ): 

```
/**
 * A list of default encoding options. Encoding and decoding in these formats
 * should be supported by the ffmpeg binary.
 * 
 * @author Joren Six
 */
public enum DefaultAttributes {
	/**
	 * Ogg, 44.1kHz sampling rate, one channel (mono), no volume change.
	 */
	OGG_MONO_44KHZ(new Attributes("ogg", "libvorbis", 44100, 1)),
	/**
	 * Ogg, 44.1kHz sampling rate, two channels (stereo), no volume change.
	 */
	OGG_STEREO_44KHZ(new Attributes("ogg", "libvorbis", 44100, 2)),
	/**
	 * Flac, 44.1kHz sampling rate, two channels (stereo), no volume change.
	 */
	FLAC_STEREO_44KHZ(new Attributes("flac", "flac", 44100, 2)),
	/**
	 * Flac, 44.1kHz sampling rate, one channel (mono), no volume change.
	 */
	FLAC_MONO_44KHZ(new Attributes("flac", "flac", 44100, 1)),
	/**
	 * MP3, 320kb/s bit rate, 44.1kHz sampling rate, one channels (mono), no
	 * volume change.
	 */
	MP3_320KBS_MONO_44KHZ(new Attributes("mp3", "libmp3lame", 44100, 1, 320000)),
	/**
	 * MP3, 320kb/s bit rate, 44.1kHz sampling rate, two channels (stereo), no
	 * volume change.
	 */
	MP3_320KBS_STEREO_44KHZ(new Attributes("mp3", "libmp3lame", 44100, 2, 320000)),
	/**
	 * MP3, 192kb/s bit rate, 44.1kHz sampling rate, one channels (mono), no
	 * volume change.
	 */
	MP3_192KBS_MONO_44KHZ(new Attributes("mp3", "libmp3lame", 44100, 1, 192000)),
	/**
	 * MP3, 192kb/s bit rate, 44.1kHz sampling rate, two channels (stereo), no
	 * volume change.
	 */
	MP3_192KBS_STEREO_44KHZ(new Attributes("mp3", "libmp3lame", 44100, 2, 192000)),
	/**
	 * MP3, 128kb/s bit rate, 44.1kHz sampling rate, one channels (mono), no
	 * volume change.
	 */
	MP3_128KBS_MONO_44KHZ(new Attributes("mp3", "libmp3lame", 44100, 1, 128000)),
	/**
	 * MP3, 128kb/s bit rate, 44.1kHz sampling rate, two channels (stereo), no
	 * volume change.
	 */
	MP3_128KBS_STEREO_44KHZ(new Attributes("mp3", "libmp3lame", 44100, 2, 128000)),
	/**
	 * WAV PCM Signed 16 bit Little Endian, one channel (mono), 8000Hz sampling
	 * rate, no volume change.
	 */
	WAV_PCM_S16LE_MONO_8KHZ(new Attributes("wav", "pcm_s16le", 8000, 1)),
	/**
	 * WAV PCM Signed 16 bit Little Endian, one channel (mono), 8000Hz sampling
	 * rate, no volume change.
	 */
	WAV_PCM_S16LE_STEREO_8KHZ(new Attributes("wav", "pcm_s16le", 8000, 2)),
	/**
	 * WAV PCM Signed 16 bit Little Endian, one channel (mono), 22050Hz sampling
	 * rate, no volume change.
	 */
	WAV_PCM_S16LE_MONO_22KHZ(new Attributes("wav", "pcm_s16le", 22050, 1)),
	/**
	 * WAV PCM Signed 16 bit Little Endian, one channel (mono), 22050Hz sampling
	 * rate, no volume change.
	 */
	WAV_PCM_S16LE_STEREO_22KHZ(new Attributes("wav", "pcm_s16le", 22050, 2)),
	/**
	 * WAV PCM Signed 16 bit Little Endian, one channel (mono), 44.1kHz sampling
	 * rate, no volume change.
	 */
	WAV_PCM_S16LE_MONO_44KHZ(new Attributes("wav", "pcm_s16le", 44100, 1)),
	/**
	 * WAV PCM Signed 16 bit Little Endian, two channel (stereo), 44.1kHz
	 * sampling rate, no volume change.
	 */
	WAV_PCM_S16LE_STEREO_44KHZ(new Attributes("wav", "pcm_s16le", 44100, 2));

	final Attributes attributes;

	private DefaultAttributes(Attributes newAttributes) {
		attributes = newAttributes;
	}

	public Attributes getAttributes() {
		return attributes;
	}

}

```

**Comment by goxr3plus** [comment]
First demo will run in Java 10 or Java 11 .... i don't know if we will have problems with Java 11 module system and Jave2.... need to test

**Comment by goxr3plus** [comment]
@a-schild  Very close to first prototype ..... i need just a little more time ... the ui is almost ready and is only missing the convert functionality .... 

![screenshot_1](https://user-images.githubusercontent.com/20374208/46261750-b01a8500-c500-11e8-92fb-7cad816b5a8b.jpg)

You like it :) ? Will add many more things :)
