### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by unix-junkie** [a-schild/jave2#27]
The original _JAVE_ is distributed under GPLv3 (see [here](http://www.sauronsoftware.it/projects/jave/)).

The `ws.schild:jave-core` module (which is an evolution of _JAVE_) lists APLv2 in its pom.xml.

The whole project, on the other hand, states that

> JAVE2 is Free Software and it is licensed under GPL 2

Is anything of the above legal?

I believe GPLv3 code can be re-licensed under neither GPLv2 nor APLv2, unless you're the author of the original code.

**Comment by goxr3plus** [comment]
@a-schild  Created #29  Pull Request

**Comment by a-schild** [comment]
Corrected to gpl v3
