### ISSUE TITLE
why always read from errorStream?

### ISSUE THREAD

**Issue by zhangys529** [a-schild/jave2#271]
i viewed many issues, and find out that they always read data from errorStream, i try to read from inputStream, but nothing. Is it normal?
just like below:
``` JAVA
ProcessWrapper ffmpeg = new DefaultFFMPEGLocator().createExecutor();
ffmpeg.addArgument("-i");
ffmpeg.addArgument(inputFilePath);
ffmpeg.execute();
BufferedReader br = new BufferedReader(new InputStreamReader(ffmpeg.getErrorStream()));
```

**Comment by a-schild** [comment]
This depends what messages you wish to receive.
Many messages relevant from ffpmeg are sent to errout, since stdout can also be used to stream out resulting images/videos
