### ISSUE TITLE
Find a way to cleverly define pom version only in one place and access also from Java Code.

### ISSUE THREAD

**Issue by goxr3plus** [a-schild/jave2#28]
So i have been searching a long time for this , how to define one time in pom.xml the application version and then access it from Java .

So we can use : 

```XML
<dependency>                            
	<groupId>org.apache.maven</groupId> 
	<artifactId>maven-model</artifactId>
	<version>3.5.4</version>            
</dependency>                           
```

and read the xml from inside the java because every time we have to define it [here](https://github.com/a-schild/jave2/blob/master/pom.xml) .

```XML
  <properties>
        <revision>2.4.4-SNAPSHOT</revision>
        <!-- Don't forget to change it also in DefaultFFMPEGLocator.java  -->
    </properties>
```

Like you know going in every pom.xml and changing the version and then in the Java code ... hm that's boring ... 

So from Java code we can access the pom.xml like this : 

```JAVA
try {                                                         
	MavenXpp3Reader reader = new MavenXpp3Reader();           
	Model model = reader.read(new FileReader("pom.xml"));     
	System.err.println("----------------------------------"); 
	System.err.println(model.getId());                        
	System.err.println(model.getGroupId());                   
	System.err.println(model.getArtifactId());                
	System.err.println(model.getVersion());                   
	System.err.println("----------------------------------"); 
                                                              
} catch (Exception ex) {                                      
	ex.printStackTrace();                                     
}                                                             
```

But that's only from inside the IDE so i will find a way to access it also easy from outside the IDE . The thing is to make our releases easier ..... not every where changing the .pom every time.

Like define version=2.5.5 , one time in one pom and boom , not changing everywhere .

What you think you like the idea?

**Comment by a-schild** [comment]
I had also searched for a solution to this, but did not come up with a good solution.
Currently I open the master pom and all dependent projects in netbeans and then do a search&replace with the old+new version numbers, just making sure to not replace it in the change logs file.

If you find another solution, I will happily use it

**Comment by goxr3plus** [comment]
Okay then my bro keep it opened i will find a solution ::)

**Comment by goxr3plus** [comment]
Damn eill right a plugin 😂
