### ISSUE TITLE
Cannot reduce size

### ISSUE THREAD

**Issue by jjsainzc** [a-schild/jave2#30]
Convert wav to mp3 cannot reduce file size

**Comment by a-schild** [comment]
@jjsainzc Please read https://medium.com/nycplanninglabs/writing-a-proper-github-issue-97427d62a20f and add more infos to your issue.

**Comment by goxr3plus** [comment]
@jjsainzc  What is the size of final .mp3 ? Tested the library on at least 50 wav files and it seems to work . Can you post the .wav file somewhere for testing ? Any errors ...

**Comment by a-schild** [comment]
See issue #31 which provides support for this
