### ISSUE TITLE
Add support for internet URL for source file

### ISSUE THREAD

**Issue by zhenghangezh** [a-schild/jave2#32]
Is it possible to add a support for getting source file from an internet URL? Currently MultimediaObject only accepts local File.
As far as I know it it possible to use an URL in "-i" parameter for ffmpeg command.

**Comment by a-schild** [comment]
Yes, this should be possible to add, but someone has to implement it. 
I will gladly apply pull requests to add this functionality

There is alredy a enhancement request in issue #23 for this (Together with the output part too)
