### ISSUE TITLE
目前不支持小程序的语音文件转换

### ISSUE THREAD

**Issue by zhangdonghaicn** [a-schild/jave2#38]
能否提供支持微信小程序的silk文件转换wav文件呢？

**Comment by a-schild** [comment]
Can you please write in english?

**Comment by WavyPeng** [comment]
> Can you please write in english?
He asked if we can use it to convert `.silk` files to `.wav` files in Wechat Mini Program?

**Comment by a-schild** [comment]
ffmpeg should have support for .silk audio files.
What happens when you try to convert them?
If it does not work, can you give me a sample silk file to test with?

**Comment by a-schild** [comment]
Closing due to missing feedback

**Comment by bingluchen** [comment]
An error occurred when I converted silk  " Invalid data found when processing input"
