### ISSUE TITLE
New features Recommendations

### ISSUE THREAD

**Issue by goxr3plus** [a-schild/jave2#39]
Today i was digging some forks of this projects and found a very interesting feature 👍 

[Generating Single Screenshot from a video](https://github.com/sdyson/jave2/commit/03a73c7f4fe3d7d368eef9a8106aa955a563ad4d)

Have we fixed this issue ?
[Fixed time parsing for videos shorter than 1 hour](https://github.com/sdyson/jave2/commit/70d3100a6cc4510859eebc2daa4673a9ab242d40)

And finally i am thinking of adding [slf4j](https://github.com/qos-ch/slf4j) as our default logger or the other one from [Google Flogger](https://github.com/google/flogger) which seems really really interesting project .

Let me know your opinions :)

**Comment by goxr3plus** [comment]
As always you know more than me .... :) 

About the `commons-logging-api` I see it hasn't been updated since 2014 ...

**Comment by a-schild** [comment]
This only means that the API is stable, the implementations below can be JDK 1.4+ logging, logback and many many others
