### ISSUE TITLE
How to upgrade the library to the Latest FFMPEG 

### ISSUE THREAD

**Issue by goxr3plus** [a-schild/jave2#4]
I want to contribute in this library , i am experienced in Java though i don't know how internally works . I mean for example , where did you found the **ffmp3-amd64.exe** for example ? In the original jave-1.0.2 can't i replace the internal ffmpeg.exe with a newer and make it work ?

Please respond this is very important for me , i am making a Media Player based on that -> https://github.com/goxr3plus/XR3Player

**Comment by goxr3plus** [comment]
Okay so i spend today 4 hours to fully understand your repository and library . Be sure that i will contribute very actively here . It's impressive . I tried the latest version of FFMPEG.exe and copied all the dlls on jave2 folder which is exporting on Windows just to check if it works , but it doesn't . We need to change the code for that ?

**Comment by a-schild** [comment]
When you replace the executables, you need to put in the fully static linked files, not depending on other dll's or other files. Currently we only handle the executables themself, no other dependencies.

**Comment by a-schild** [comment]
About ffmpeg 4.x

https://www.ffmpeg.org/index.html#news

Beside more formats/codec support, the main improvements seems to be in hardware encoding/decoding support for some intel/amd/nvidia hardware.

FFmpeg 4.0 is now available as the latest major release for this widely-used open-source multimedia encode/decoder library.

FFmpeg 4.0 introduces NVIDIA NVDEC GPU-based decoding for H264 / MJPEG / HEVC / MPEG-1/2/4, VC1, VP8, and VP9 formats. This release also adds an Intel QSV accelerated overlay filter, an OpenCL overlay filter, VA-API MJPEG and VP8 decoding support, new VA-API filters, and many other accelerated code path improvements.

The FFmpeg release also drops support for Windows XP, now supports LibreSSL, and adds a number of new filters, encoders, and decoders. 

This commes with a drawback in file sizes.
The initial native-win-64 jar file had 8.5MB in size
The current one with ffmpeg 3.4.2 is already 17MB
And the 4.0 version results in a 21MB jar per platform, including all 5 platforms results in ~100MB jar's to deploy

**Comment by goxr3plus** [comment]
That's amazing. Yes i inspected carefully your emaila amd the size of
files. I think we have to update the code also? The ProgressListener is not
working for some strange reason, i read the code and the problem is
somewhere in an if statement checking for frame.

**Comment by a-schild** [comment]
With the current version the progress listener should work.
At least in the unit test testEncode4argsLarge3 gives 3 progress calls to the listener.

Please open a new issue if you can reproduce it with the current code (Please including some sample code + files)

**Comment by a-schild** [comment]
For ffmpeg 4 it looks like the output is backward compatible, but I haven't done extensive tests

**Comment by goxr3plus** [comment]
Great i will check right soon. It's amazing that you started replying so
fast :) So happy.
