### ISSUE TITLE
Does it support the format speex?

### ISSUE THREAD

**Issue by WavyPeng** [a-schild/jave2#40]
Hi, I meet a problem in my project that I should convert `.speex` to `.wav` or `.mp3`.
I think if `jave2` can help me do this.
Thank you :)

**Comment by a-schild** [comment]
The included ffmpeg binaries have speex support built in, so I think it should just work out of the box.
Have you tried it?
If not, please show your code and the input file(s)

**Comment by WavyPeng** [comment]
I've tried to covert `.speex` to `.mp3` with `jave2`. My code and input file are as follows:

```
File target = File.createTempFile("asr_des_tmp", ".mp3");
AudioAttributes audio = new AudioAttributes();
audio.setCodec("libmp3lame");
audio.setBitRate(128000);
audio.setChannels(1);
audio.setSamplingRate(16000);
EncodingAttributes attrs = new EncodingAttributes();
attrs.setFormat("mp3");
attrs.setAudioAttributes(audio);
Encoder encoder = new Encoder();
encoder.encode(new MultimediaObject(source), target, attrs);
```
![image](https://user-images.githubusercontent.com/26155781/50875785-dd7ea500-1404-11e9-90ae-4d5e7f82b92b.png)

However, I meet the `InputFormatException`:

![image](https://user-images.githubusercontent.com/26155781/50875911-6695dc00-1405-11e9-9545-6c10bab9951e.png)

Is there anything I did wrong? Such as I used the wrong `codec`.

**Comment by a-schild** [comment]
Closing due to missing feedback
