### ISSUE TITLE
Problem encoding multi-channel vorbis audio

### ISSUE THREAD

**Issue by ekalyvio** [a-schild/jave2#43]
Hi. I have the following source code and I try to encode a **four channel** OGG-vorbis file to a **four channel** flac.

```
        File source = new File("source.ogg");
        File target = new File("target.flac");
        
        AudioAttributes audio = new AudioAttributes();
        audio.setCodec("flac");
        audio.setBitRate(new Integer(360000));
        audio.setChannels(new Integer(4));
//        audio.setVolume(new Integer(1000));
//        audio.setQuality(new Integer(1000));
        audio.setSamplingRate(new Integer(48000));
        EncodingAttributes attrs = new EncodingAttributes();
        attrs.setFormat("flac");
        attrs.setAudioAttributes(audio);
        
        Encoder encoder = new Encoder();
        
        String formats[] = null;
        try {
            System.out.println("Supported decoding formats");
            System.out.println("--------------------------");
            formats = encoder.getSupportedDecodingFormats();
            for (String frm : formats) { System.out.println(frm); }
            
            System.out.println("Supported encoding formats");
            System.out.println("--------------------------");
            encoder.getSupportedEncodingFormats();
            for (String frm : formats) { System.out.println(frm); }
            
            System.out.println("Audio decoders");
            System.out.println("--------------");
            formats = encoder.getAudioDecoders();
            for (String frm : formats) { System.out.println(frm); }
                    
            System.out.println("Audio encoders");
            System.out.println("--------------");
            formats = encoder.getAudioEncoders();
            for (String frm : formats) { System.out.println(frm); }
        } catch (EncoderException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            MultimediaObject mo = new MultimediaObject(source);

            MultimediaInfo info = mo.getInfo();
            System.out.println(info.getAudio().getBitRate());
            System.out.println(info.getAudio().getChannels());
            System.out.println(info.getAudio().getDecoder());
            System.out.println(info.getAudio().getSamplingRate());
            
            encoder.encode(mo, target, attrs);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (EncoderException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }/* catch (InputFormatException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }*/

```
There are various problems reading the source file.
1) The getBitRate() of MultimediaInfo returns 959. It seems totally strange bitrate and really low.
2) The channel counts are reported as -1.
3) When encoding it to flac, the flac ends having 4 channels but only the first 2 are valid as the 3rd is empty and the 4th has the combination of the 3rd and 4th channel. (Please check both source and target files and you will understand - they do contain only DTMF tones). It actually reports:
`INFO: Unhandled message in step: 2 Line: 10 message: <[flac @ 000002414c2c5cc0] Channel layout not supported by Flac, output stream will have incorrect channel layout.>`
4) Finally, there is no documentation for the setVolume & setQuality functions. What is the range of their parameters? The setVolume complains and reports the following:
`Feb 19, 2019 4:28:40 PM ws.schild.jave.ConversionOutputAnalyzer analyzeNewLine
INFO: Unhandled message in step: 2 Line: 7 message: <-vol has been deprecated. Use the volume audio filter instead.>
Feb 19, 2019 4:28:40 PM ws.schild.jave.ConversionOutputAnalyzer analyzeNewLine
INFO: Unhandled message in step: 2 Line: 8 message: <-vol is forwarded to lavfi similarly to -af volume=3.906250.>
`
I attach also a screenshot of the input and the wrong output waveforms.

![waveforms](https://user-images.githubusercontent.com/3956939/53022716-6c4efa80-3464-11e9-83f3-36b8bfcf725d.jpg)

[4chan.zip](https://github.com/a-schild/jave2/files/2880357/4chan.zip)

**Comment by a-schild** [comment]
The issues 1+2 are now corrected.
- The bitrate was returned in kBps instead of Bps
- The channel detection did only work for mono+stereo, but not for quad (It does still not work for others)

**Comment by a-schild** [comment]
@ekalyvio When you don't specify the number of channels, the covnersion works fine.
This is because the channel layout is then copied over from the input.
When you specify the 4 channels, it does build up a 4.0 layout and not the quad layout your are expecting.

Is your usecase a real one, where you need to specify the number of output channels?

**Comment by ekalyvio** [comment]
I only need to encode the ogg file to flac with the same 4 channels (without merging any channels to stereo or mono - meaning I need them as the original file). Nothing else.
If I don't need to specify the channel number to get encoded as it is, then I don't have any problem. I will delete that line of code.
What about the bitrates and the sampling rates? Will it use the original's file information to encode it to flac if I don't specify them?

**Comment by a-schild** [comment]
The setVolume is a factor
     * 2560 is volume=20dB
     * The formula is dBnumber=20*lg(amplitude ratio)
     * 128 means reducing by 50%
     * 512 means doubling the volume

I added it to the javadoc.
The warning can currently be ignored, it's using a old argument, but it still works with ffmpeg

**Comment by ekalyvio** [comment]
What about the setQuality? Which value is the greatest quality?
I assume that lowest is 0?

**Comment by a-schild** [comment]
The value depends on the choosen codec

     * For mp3 you can see here:
     * https://trac.ffmpeg.org/wiki/Encode/MP3

     * Or more general
     * https://ffmpeg.org/ffmpeg-codecs.html

I added this to the javadoc
