### ISSUE TITLE
cannot get the duration of the aac audio

### ISSUE THREAD

**Issue by lchpersonal** [a-schild/jave2#48]
i have two acc audios，use jave to calculate the duration， one of them is correct，the other  get -1. how can i get the real duration？

the result：

0.aac: 60050
1.aac: -1

i use the music player，all of them can run correct。

**Comment by lchpersonal** [comment]
here is the audios：
link ： https://pan.baidu.com/s/1aT7PPHHtSioJuquOulvH6A 
password：ssqp

**Comment by a-schild** [comment]
@lchpersonal any chance to plcae the files somewhere else?
I can login, but I don't find the download function in the chinese UI... :(
Most of the clicks lead me to yet another login or a download of some exe files

**Comment by a-schild** [comment]
Will close this issue in a few days, since not receiving a test file
