### ISSUE TITLE
video interception api could not be found

### ISSUE THREAD

**Issue by xiaoLee1993** [a-schild/jave2#49]
i need to use ffmepg to intercept video and add logo？

maybe like this ？

new DefaultFFMPEGLocator().createExecutor().addArgument()…………

**Comment by a-schild** [comment]
Can you show me in ffmpeg terms / command line arguments what you would need to do?
I can then enhance the api to allow this too if it makes sense for other users too

**Comment by xiaoLee1993** [comment]
maybe like this? 

intercept the first second image
ffmepg -i input.mp4 -y -f image2 -ss 00:00:01 -vframes 1 target.png

add a logo
ffmpeg -y -i input.mp4 -vf "movie='logo.png' [logo];[in][logo] overlay=10:10:1 [out]" output.mp4

and other video clipping operations？  

i can use the command to implement them but I think it might be more helpful to use encapsulated apis

**Comment by a-schild** [comment]
Capturing image(s) from the video is already possible.
Look at the jave-core/src/main/java/ws/schild/jave/ScreenExtractor.java class.

The method `render(..)` will extract one/multiples images in the specified file/directory

I haven't used it myself in a long time and test converage is not present, so you would need to test it yourself. If you find bugs in that part, please open new issues for them.

I will keep this issue as an RFE to add logo to the video
If you need video clipping, then please open a separate issue for this too

**Comment by xiaoLee1993** [comment]
this is great.    clipping is not currently required   
the current requirements are images and adding watermarks
i'll probably do it based on your code
thanks
