### ISSUE TITLE
Difference between other ffmpeg wrapper, especially javacv?

### ISSUE THREAD

**Issue by TonalidadeHidrica** [a-schild/jave2#50]
I've been looking for ffmpeg wrapper for Java and found [javacv](https://github.com/bytedeco/javacv) seemingly useful.  That was few weeks ago.  However recently I found this java2e project (via [XR3Player](https://github.com/goxr3plus/XR3Player) and [java-stream-player](https://github.com/goxr3plus/java-stream-player)) and found that this is also actively developed, and nice-looking library.  So I want to ask you what is, if you ever know about javacv, difference between those two (and possibly any other ffmpeg Java wrapper)?

**Comment by a-schild** [comment]
I haven't looked at all the ffmpeg wrappers available when I did take over this project some years ago, so I can't answer this.

In the last year we did some major improvements and will continue to add small features.
javacv seems to be a "i can everything" library, jave2 on the other side has a very clear focus.

**Comment by TonalidadeHidrica** [comment]
Thanks for the reply.  What is the "clear focus" of your project?

**Comment by a-schild** [comment]
The focus is to provide a ffmpeg wrapper, but nothing more.
The api will be extended as requested by users of the library

**Comment by TonalidadeHidrica** [comment]
I see.  Thank you for answering.
