### ISSUE TITLE
convert .amr to mp3 failed

### ISSUE THREAD

**Issue by c513326** [a-schild/jave2#51]
File source = new File("one.amr");
        File target = new File("two.mp3");

        AudioAttributes audio = new AudioAttributes();
        audio.setCodec("libmp3lame");
//        audio.setBitRate(new Integer(128000));
//        audio.setChannels(new Integer(2));
//        audio.setSamplingRate(new Integer(44100));
        EncodingAttributes attrs = new EncodingAttributes();
        attrs.setFormat("mp3");
        attrs.setAudioAttributes(audio);
        try {
            Encoder encoder = new Encoder();
            encoder.encode( new MultimediaObject(source), target, attrs);
        } catch (Exception e) {
            e.printStackTrace();
        }

run  exception:
ws.schild.jave.InputFormatException: Invalid data found when processing input
	at ws.schild.jave.MultimediaObject.parseMultimediaInfo(MultimediaObject.java:171)
	at ws.schild.jave.MultimediaObject.getInfo(MultimediaObject.java:113)
	at ws.schild.jave.Encoder.encode(Encoder.java:546)
	at ws.schild.jave.Encoder.encode(Encoder.java:357)
	at com.yanhua.demo.service.TestService.changeToMp3(TestService.java:67)
	at com.yanhua.demo.service.TestService.main(TestService.java:18)

**Comment by a-schild** [comment]
Could you please also attach the mp3 which which gives the problem?
Loooks like it is corrupted in some way...

**Comment by c513326** [comment]
> Loooks like it is corrupted in some way...

but we convert wav to mp3  success .  so  I not understand

**Comment by a-schild** [comment]
Sorry, i mean please attach the source file (In your case the .arm file)

**Comment by c513326** [comment]
[2019V7HR.ZIP](https://github.com/a-schild/jave2/files/3196629/2019V7HR.ZIP)

**Comment by a-schild** [comment]
When we run "ffmpeg -i 2019V7HR.arm" ffmpeg in versions 4.1 and 4.1.3 returns "2019V7HR.amr: Invalid data found when processing input"

This means that the metadata are corrupt and ffmpeg can't extract the format/duraction etc.
There is no way we can fix this, since the input file is corrupt.

The conversion however can still work, since it does not need to analyze all metadata for the conversion.

**Comment by c513326** [comment]
ok
