### ISSUE TITLE
Can not use Jave2 with Java 11

### ISSUE THREAD

**Issue by goxr3plus** [a-schild/jave2#52]
I am trying to use Jave2 with `Java 11` because i passed XR3Player in Java 11 =>

But i am getting this error :

``` JAVA
Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for C:\Users\akentros\.m2\repository\ws\schild\jave-native-win64\2.4.6\jave-native-win64-2.4.6.jar
Caused by: java.lang.IllegalArgumentException: jave.native.win64: Invalid module name: 'native' is not a Java identifier

```

**Comment by goxr3plus** [comment]
@a-schild  Please guide me on how to resolve . It seems Java 11 can't handle jave.native.win64 .

**Comment by goxr3plus** [comment]
@a-schild  Saw your latest commits , you are awesome , i am new to Java 9/11 and trying to understand how to pass this project to be compatible.

**Comment by a-schild** [comment]
I think there are two ways to make in java 9+ compatible.
- Rename the xxx-native-yyyy jars to something without native in the name. (It's a reserved word in java 9 and since it constructs a module path from the jar name it breaks)
- Add a module-info.java to each class and change the minimum java version to 9

I think I will try with renaming the jar files, this way we could remain compatible with java 8

**Comment by goxr3plus** [comment]
@a-schild  I absolutely agree.

One more problem here , since Jave2 is using `commons.logging.api` and i am using in my project `commons.logging` the app is crashing at the begginning giving me the below error :  

``` JAVA
Error:java: module jave.native.linux32 reads package org.apache.commons.logging.impl from both commons.logging.api and commons.logging
```

what can i do for that , since Jave2 has by default `commons.logging.api`.

**Comment by a-schild** [comment]
Can you please checkout the java9 branch from here:

https://github.com/a-schild/jave2/tree/java-9

Then build the targets and then in your own application reference the jave2-nativebin-XXXX modules instead of jave2-native-XXXX ?

**Comment by goxr3plus** [comment]
@a-schild  I will fork and try to use , though i have the error  mentioned above and i can't continue . 

```
Error:java: module jave.native.linux32 reads package org.apache.commons.logging.impl from both commons.logging.api and commons.logging
```

I don't have a clue how to resolve it.

**Comment by goxr3plus** [comment]
@a-schild  Forked it and using it with JitPack , it seems to work fine except the above error.

**Comment by goxr3plus** [comment]
Okay it works like charm , i excluded `jave-example` and jave-core-test` so no conflicts on the `logging-api` , you can release version 2.4.8

@a-schild I am waiting for it :)

**Comment by a-schild** [comment]
I did just publish the 2.5.0 release. (I did use a 2.5 since we did change the maven dependencies from xxx-native-yyy to xxx-nativebin-yyy

Might take some time until it's available in maven central

**Comment by goxr3plus** [comment]
@a-schild  You are awesome thank you :)
