### ISSUE TITLE
Let's add Sponsor Button

### ISSUE THREAD

**Issue by goxr3plus** [a-schild/jave2#53]
I think this is a new functionality on Github.

You can go to settings :

![chrome_2019-05-31_11-05-47](https://user-images.githubusercontent.com/20374208/58691246-10b1d880-8394-11e9-936a-641093d1503e.png)

And put your links for Sponsoring.

Checkout how it looks for XR3Player :

![chrome_2019-05-31_11-06-27](https://user-images.githubusercontent.com/20374208/58691278-26270280-8394-11e9-9836-d10d1adf7d2c.png)

Below is an example file (**Modify it on your needs so it points your paypal and stuff**) :

``` JAVA
# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: GOXR3PLUSTUDIO
open_collective: # Replace with a single Open Collective username
ko_fi: goxr3plusstudio
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://www.paypal.me/GOXR3PLUSCOMPANY

```

**Comment by a-schild** [comment]
Currently I don't plan to do it this way.
And I also think, that we will not attract enough followers to have some cache back.

Or have you some experience from other projects?

**Comment by goxr3plus** [comment]
It's a new functionality from Github, i have seen this button in many projects i adde it in all of mine. It's like a 5 minutes task, not bad to have :)

**Comment by a-schild** [comment]
For this project I won't add the button as of now.
Perhaps later...
