### ISSUE TITLE
Could not find ffmpeg executable for native/ffmpeg-amd64.exe is the correct platform jar included? java.lang.NullPointerException

### ISSUE THREAD

**Issue by goxr3plus** [a-schild/jave2#54]
I am trying to use Jave2 version 2.5.0 today and i am getting the below error :

``` java
Jun 06, 2019 5:41:36 PM ws.schild.jave.DefaultFFMPEGLocator copyFile
SEVERE: Could not find ffmpeg executable for native/ffmpeg-amd64.exe is the correct platform jar included?
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.nio.file.Files.copy(Files.java:3109)
	at jave.core@2.5.0/ws.schild.jave.DefaultFFMPEGLocator.copy(DefaultFFMPEGLocator.java:167)
	at jave.core@2.5.0/ws.schild.jave.DefaultFFMPEGLocator.copyFile(DefaultFFMPEGLocator.java:132)
	at jave.core@2.5.0/ws.schild.jave.DefaultFFMPEGLocator.<init>(DefaultFFMPEGLocator.java:92)
	at jave.core@2.5.0/ws.schild.jave.Encoder.<init>(Encoder.java:86)
	at XR3Player/com.goxr3plus.xr3player.xplayer.waveform.WaveFormService$1.transcodeToWav(WaveFormService.java:364)
	at XR3Player/com.goxr3plus.xr3player.xplayer.waveform.WaveFormService$1.processFromNoWavFile(WaveFormService.java:207)
	at XR3Player/com.goxr3plus.xr3player.xplayer.waveform.WaveFormService$1.call(WaveFormService.java:158)
	at XR3Player/com.goxr3plus.xr3player.xplayer.waveform.WaveFormService$1.call(WaveFormService.java:142)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Service.java:725)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Service.java:724)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

Solution :

(DefaultFFMPEGLocator.java:167) => change `native` to `nativebin`  ?

Let me know .

**Comment by a-schild** [comment]
Strange, this works for me on Windows 10 64bit.
What JRE/JDK Version do you use?

**Comment by goxr3plus** [comment]
11 and today tried also with 12. You can see the pom.xml of XR3Player.

**Comment by goxr3plus** [comment]
Windows 64 bit too.

**Comment by a-schild** [comment]
Hmmm...

I could build the XR3Player project, but running does not work (JDK12)

I did add all the vm options as mentioned in the readme.

On startup this is shown as error:

`Error: JavaFX runtime components are missing, and are required to run this application`

**Comment by goxr3plus** [comment]
Did you runned Maven so it downloads dependencies?

**Comment by goxr3plus** [comment]
Very strange maybe it has no permissions to copy or something i wil test
again today.

**Comment by a-schild** [comment]
Any chance in adding a run target in the pom file?

https://stackoverflow.com/questions/1089285/maven-run-project

**Comment by goxr3plus** [comment]
Are you using IntelliJ?

**Comment by goxr3plus** [comment]
It wil start with errors but finally it will show the main window

**Comment by goxr3plus** [comment]
Oh i have not tested id the Maven clean package works, but just runned with IntelliJ 2019 configuration of Java 12

**Comment by a-schild** [comment]
I'm running it in Netbeans 11

**Comment by goxr3plus** [comment]
How you are adding the VM Parameters ?

**Comment by a-schild** [comment]
Can you please try with 2.5.1-SNAPSHOT?
I just renamed the executable folders to match.
Probably this solves the problem.

**Comment by goxr3plus** [comment]
Yes thank you i will try the new version and let you know.

**Comment by goxr3plus** [comment]
@a-schild  I saw the changes on latest commits , are we dropping Java 8 for this library ?

**Comment by a-schild** [comment]
No, java8 is still the minimum.
But I added a test-target for java 11

**Comment by goxr3plus** [comment]
@a-schild  Testing now with 2.5.1 snapshot

**Comment by goxr3plus** [comment]
Still the same error :

``` JAVA

SEVERE: Could not find ffmpeg executable for nativebin/ffmpeg-amd64.exe is the correct platform jar included?
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.nio.file.Files.copy(Files.java:3109)
	at jave.core@2.5.1/ws.schild.jave.DefaultFFMPEGLocator.copy(DefaultFFMPEGLocator.java:167)
	at jave.core@2.5.1/ws.schild.jave.DefaultFFMPEGLocator.copyFile(DefaultFFMPEGLocator.java:132)
	at jave.core@2.5.1/ws.schild.jave.DefaultFFMPEGLocator.<init>(DefaultFFMPEGLocator.java:92)
	at jave.core@2.5.1/ws.schild.jave.Encoder.<init>(Encoder.java:86)
	at XR3Player/com.goxr3plus.xr3player.xplayer.waveform.WaveFormService$1.transcodeToWav(WaveFormService.java:363)
	at XR3Player/com.goxr3plus.xr3player.xplayer.waveform.WaveFormService$1.processFromNoWavFile(WaveFormService.java:206)
	at XR3Player/com.goxr3plus.xr3player.xplayer.waveform.WaveFormService$1.call(WaveFormService.java:157)
	at XR3Player/com.goxr3plus.xr3player.xplayer.waveform.WaveFormService$1.call(WaveFormService.java:141)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Service.java:725)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Service.java:724)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)

```

I don't know why is this happening . Running with Java 12 .

**Comment by goxr3plus** [comment]
I will download the repository locally and use breakpoints to see exactly what happens .

**Comment by goxr3plus** [comment]
Found a very strange behaviour , i made a small test for the application like :

``` JAVA
class TestJave2 {

	@DisplayName("Test Jave2 DefaultFFMPEGLocator")
	@Test
	void testJaveInits() {

		new DefaultFFMPEGLocator();
	}
}

```

And deleted the .exe from the jave folder in windows . It runs okay from the test .

Now trying to start the application and putting somewhere randomly -> `new DefaultFFMPEGLocator();` 

And i get the error . What kind of **black magic** is this .

**Comment by goxr3plus** [comment]
Has that to do with Java 11 probably something changed ?

I have not understood the mechanism how the application actually detects native/xxxx.exe in runtime ? Can you send me some article to read about it. 

I have added on the main method of the application :

```JAVA
	public static void main(final String[] args) {

		//Init Jave 2
		new DefaultFFMPEGLocator();

		// Launch JavaFX Application
		launch(args);
	}
```

**Comment by goxr3plus** [comment]
I have added on the module-info : 

```JAVA
	requires jave.core;
	requires jave.nativebin.win64;
```

i am going crazy i will cry . It doesn't work again.

**Comment by a-schild** [comment]
I think to test yo must make sure to empty your %TEMP%\temp\jave folder, otherwise the system sess an existing ffmpeg executable and uses this one.

The native executable is selected based on this code in `DefaultFFMPEGLocator`

```

String os = System.getProperty("os.name").toLowerCase();
        boolean isWindows = os.contains("windows");
        boolean isMac = os.contains("mac");
        LOG.debug("Os name is <"+os+"> isWindows: "+isWindows+" isMac: "+isMac);

        // Dir Folder
        File dirFolder = new File(System.getProperty("java.io.tmpdir"), "jave/");
        if (!dirFolder.exists())
        {
            LOG.debug("Creating jave temp folder to place executables in <"+dirFolder.getAbsolutePath()+">");
            dirFolder.mkdirs();
        }
        else
        {
            LOG.debug("Jave temp folder exists in <"+dirFolder.getAbsolutePath()+">");
        }

        // -----------------ffmpeg executable export on disk.-----------------------------
        String suffix = isWindows ? ".exe" : (isMac ? "-osx" : "");
        String arch = System.getProperty("os.arch");

        //File
       File ffmpegFile = new File(dirFolder, "ffmpeg-" + arch +"-"+MY_EXE_VERSION+ suffix);

```

The actual copy then happens som elines below:

```
private void copyFile(String path, File dest) {
        String resourceName= "nativebin/" + path;
        try
        {
            LOG.debug("Copy from resource <"+resourceName+"> to target <"+dest.getAbsolutePath()+">");
            if (copy(getClass().getResourceAsStream(resourceName), dest.getAbsolutePath()))
{

```

In your case it lokks like the `getClass().getResourceAsStream()` fails...

**Comment by goxr3plus** [comment]
Today made a completely new small project with just a Main.class and Java 11 module . 

1) I tested creating my own DefaultFFMPEGLocator
2) Tested using the already existing DefaultFFMPEGLocator

I tried with debugger and below i am attaching the images to show you what happens .

![idea64_2019-07-15_17-34-00](https://user-images.githubusercontent.com/20374208/61224289-015dd300-a727-11e9-92da-e9c459839b15.png)
![idea64_2019-07-15_17-34-05](https://user-images.githubusercontent.com/20374208/61224292-01f66980-a727-11e9-8413-f4d21bdc6df0.png)
![idea64_2019-07-15_17-34-12](https://user-images.githubusercontent.com/20374208/61224293-01f66980-a727-11e9-9f36-7d5ebc1edaf2.png)


I also uploaded it on the github so you can run it also and tell me if it works for you.
For me it's always null/

https://github.com/goxr3plus/jave2-problems

@a-schild  Please check and run the repo i made , it's the latest code you have commited until today .

**Comment by goxr3plus** [comment]
Java 11 damn => https://stackoverflow.com/questions/54021754/why-does-the-getresource-method-return-null-in-jdk-11

**Comment by goxr3plus** [comment]
I will add an empty class inside the jave-nativebin as described here to check => https://stackoverflow.com/questions/47613602/java-9-0-classloadergetresourceasstream-nullpointerexception

**Comment by goxr3plus** [comment]
https://stackoverflow.com/questions/46861589/accessing-resource-files-from-external-modules

I am done.... from life.

**Comment by goxr3plus** [comment]
I think i got it working using :

```
    private void copyFile(String path, File dest) {
        String resourceName= "ws/schild/jave/nativebin/" + path;
```

**Comment by a-schild** [comment]
@goxr3plus Do you implement your own DefaultFFMPEGLocator class?
When I run your text project, then it fails.
When I run the same test project, but reference to `ws.schild.jave.DefaultFFMPEGLocator locator  = new ws.schild.jave.DefaultFFMPEGLocator();` the executables are found.

I think this is because "your" locator is in another package, and has no access to the internals of the jave jar's

**Comment by goxr3plus** [comment]
I tried today with 

```
ws.schild.jave.DefaultFFMPEGLocator locator = new ws.schild.jave.DefaultFFMPEGLocator(); 
```

Exactly the same code , with Java 12 , i think the computer has a problem or IntelliJ

**Comment by goxr3plus** [comment]
For now i will use my FFMPEGLocator with 

```
   /**
     * Copies a file bundled in the package to the supplied destination.
     *
     * @param path The name of the bundled file.
     * @param dest The destination.
     * @throws RuntimeException If an unexpected error occurs.
     */
    private void copyFile(String path, File dest) {
        String resourceName= "ws/schild/jave/nativebin/" + path;
        try
        {
            InputStream is= ClassLoader.getSystemResourceAsStream(resourceName);
            if (is != null)
```

Can we add this code on the library so it works everytime and i don't have to implement my own Locator?

**Comment by goxr3plus** [comment]
And adding this let's have a new release also 2.5.1 because i am ready to use it on XR3Player :)

**Comment by goxr3plus** [comment]
I did a commit , can you let me know if you agree with it and if it works for you ? Like i see no other solution on my computers ...

**Comment by goxr3plus** [comment]
For now i forked the latest repo commit , tried with XR3Player and it works like charm.

https://jitpack.io/#goxr3plus/jave2/2.5.4


Let me know when you can release a new version from here :)

**Comment by a-schild** [comment]
@goxr3plus I did change the code to use both methods if required.
This way we will have less regressions for existing environment.

Can you please try with the official 2.5.1-SNAPSHOT I just published?
If it's OK, I will make a 2.5.1 final build

In the 2.5.2 I will change the loggin api

**Comment by goxr3plus** [comment]
@a-schild  Okay i read the code , we are ready to go , it will work . Good though to have a fallback .

**Comment by runnermann** [comment]
Hello, This still seems to be an issue. I installed using Gradle. I am using osx and Java 1.8 . I resolved the issue by manually installing the ffmpeg-x86_64osx into the appropriate folder provided in the error message. I also had to rename the file by adding the "-2.6.0-osx" at the end of the file name so it matched the error. This resolved this problem.

**Comment by a-schild** [comment]
What OSX version are you running?

**Comment by runnermann** [comment]
Hello André, 

I am using OSX version 10.13.6 on a late 2012 Mac-Mini. 

I have manually installed the ffmpeg-x86-osx into the location that was provided in the error message. I am not sure where the location for the installation is coming from. Once I manually installed the ffmpeg file it ran fine until I rebooted the Mac the next day. I had to manually re-install the ffmpeg file into the same location. I also had to change the name of the file to match the error message. 


- The full path location:   Home/private/var/folders/yz/32n0zp2n5wdd_55hw0xf2jvh0000gn/T/jave/ffmpeg-86_64-2.6.0-osx


I am using Gradle to build and track dependencies. 

- Here is what I used under dependencies

// Convert video types to MPG4
compile group: 'ws.schild', name: 'jave-all-deps', version: '2.6.0'




Gradle does show that the ffmpeg executables for linux, windows, and osx are included. 

Also, when I build an exportable app, the osx ffmpeg executable is no longer accessible and this feature does not work. I will also check on a Windows 10 system and see if the same problem exists after the App has been built. 

-L

**Comment by runnermann** [comment]
The ffmpeg exe is not accessible from an app built using Win10.

**Comment by runnermann** [comment]
Found an issue with the file copy in DefaultFFMPEGLocator. 
1) In line 46: It appears that there is a version that is being added to the String executable file name that is not necessary. IMHO unless or until the executable is changed/updated, this field and it's use on line 80 is not necessary. 
2) I recommend modifying the installation/locator location to remain within the Sandbox of an application. Replace current code and provide a relative path.
3) I have not attempted to re-encode long files, however, if possible, this may be a good area for multi-core processing. The downside is, the safest and easiest to implement multi-core libraries are Java 8.  

I will implement and test the above modifications.

**Comment by a-schild** [comment]
@runnermann 
1.
- We use the version string, to have matching jar + executables, otherwise the command line arguments and output parsing could break
- Imagin a server where multiple versions of jave libraries are active, if we don't version the executable, then we get a mixup

2. The executables are shipped inside of jar files, so we need to extract them and place them somewhere where the java application has write rights.
The temp folder was so far the best place we did find, since there the application has write rights.
If you have another working solution I will be glad to apply a patch

3. The ffmpeg used is using as much cores as possible when doing decoding/encoding work.
It depends on the codecs if they can use more than one core.
In jave 2.6.x you can specify to not use more than X cores for a single conversion process
If you re-encode a single input file into different output formats/qualities, then you can call the encode method concurrently, this works fine and you have control over the number of cores used and the order/priority in which you wish to have the formats generated.

**Comment by a-schild** [comment]
@runnermann I have done a test project on OS X 10.12.6 with java 8 and java 12 and for me it works with cradle too.

Could you please check if the correct jar files are included in the final gradle output?
If it still fails, please open a separate issue and post the sample project there, along with the used java version etc.
