### ISSUE TITLE
What is the purpose of jave-example ?

### ISSUE THREAD

**Issue by goxr3plus** [a-schild/jave2#55]
So we have  https://github.com/a-schild/jave2/blob/5472879d288905ad51f9a58fa52e79555656628f/jave-example/src/main/java/ws/schild/jave/example/DefaultFFMPEGLocatorTest.java#L28-L35

How we can run this locally as it will always fail on the copy method as it always fails . What is the intention of jave-example class ?

Also i see on the basic pom.xml  https://github.com/a-schild/jave2/blob/5472879d288905ad51f9a58fa52e79555656628f/pom.xml#L33-L46 plugins have outdated version .. is this intentional or it is meant to be like that ?

**Comment by a-schild** [comment]
I think we could remove this project/target.
It was once intended to have example usages as code in there, but in the tests we have also some sample usages.

**Comment by goxr3plus** [comment]
@a-schild  Andre i don't undertand something. 

Let's say i have an application in Java-11 , a simple one and i start it , i create a https://github.com/a-schild/jave2/blob/master/jave-core/src/main/java/ws/schild/jave/DefaultFFMPEGLocator.java which copies the needed .exe to the folder.

How it detects it inside the .jar file where it is .... i really cannot understad,can you help me ?

**Comment by a-schild** [comment]
It does not matter in which jar file it is.
Since we use the class loader to resolve the resource, according to the java namesapces, it's the class loader which finds the correct jar file, where the resource is stored.

The `ClassLoader` has a method called `.getResourceAsStream()` for this (Which is used in the copyFile method of the default ffmpeglocator.)

**Comment by goxr3plus** [comment]
@a-schild  I am trying to understand why it doesn't work in XR3Player anymore , like it's madness .

**Comment by a-schild** [comment]
Could you make a very smal sample app which has the same problem?

**Comment by a-schild** [comment]
Could you please do this check:
Remove all jave-nativebin*.jar files with the exception of the one you need and then start the application?
