### ISSUE TITLE
Use modern logger api

### ISSUE THREAD

**Issue by a-schild** [a-schild/jave2#56]
The currently used commons logging api is very old scool.
Currently we consider switching to either SLF4J or Log4J2

Advantages of SLF4J (v2)  -> Used in Spring applications -> Large basis
Advantages of Log4J2 -> Modern API, fastest known logging solutions as of 2019

Any comments for users of the library?

https://logging.apache.org/log4j/2.x/manual/index.html

**Comment by eppjo** [comment]
I recommend to use slf4j. 
If you use 3rd party libraries using different logging frameworks, such as `java.util.logging' , `java.commons.logging` or even `log4jxxx`, they all can easily be bridged to slf4j.

**Comment by a-schild** [comment]
From 2.6.0 on we will use SLF4J in version 1.7.x
