### ISSUE TITLE
Concatenation of audio files

### ISSUE THREAD

**Issue by eppjo** [a-schild/jave2#57]
I like this awesome library that makes converting media files so easy.
One wish is to be able to concatenate audio files (maybe also video files) to one single audio/video.
Example:

`track1.mp3 + track2.mp3 + ... + trackn.mp3 ==> audio.mp3`

Here the link to [ffmpeg/concatenate](https://trac.ffmpeg.org/wiki/Concatenate)

**Comment by a-schild** [comment]
Could you please make a proposal furch the API.
I think we could pass in a collection of `MultimediaObject`

We would also probably need to enahnce `MultimediaObject` to accept URL's as sources

**Comment by goxr3plus** [comment]
@eppjo  Great feature :) !!!

**Comment by a-schild** [comment]
The new 2.6.0-SNAPSHOT release allows you to pass a list of `MultimediaObject` to the encoder class, so they get concated.

Works for audio and video files too

**Comment by goxr3plus** [comment]
@a-schild  Let's add code examples for that.
