### ISSUE TITLE
Do you support transcoding from remote

### ISSUE THREAD

**Issue by yueyou16** [a-schild/jave2#61]
Do you support transcoding from remote

**Comment by a-schild** [comment]
Hello @yueyou16 ,

in the latest 2.6.0-SNAPSHOT you can specify URL's instead of files for the input.

**Comment by yueyou16** [comment]
thank you

**Comment by yueyou16** [comment]
Can you give me the 2.6.0-snapshot version of the code

**Comment by yueyou16** [comment]
> 你好@yueyou16，
> 
> 在最新的2.6.0-SNAPSHOT中，您可以指定URL而不是输入文件。

Can you give me the 2.6.0-snapshot version of the code

**Comment by yueyou16** [comment]
> Hello @yueyou16 ,
> 
> in the latest 2.6.0-SNAPSHOT you can specify URL's instead of files for the input.

When is the latest version of 2.6.0-snapshot likely to be released

**Comment by a-schild** [comment]
You can already use it either with maven or any other build tool which handles the dependencies.
Just specify 2.6.0-SNAPSHOT as the version.

The sources itself are here on github.

So far I havent a release date, but I think in 1-2 weeks

**Comment by yueyou16** [comment]
> You can already use it either with maven or any other build tool which handles the dependencies.
> Just specify 2.6.0-SNAPSHOT as the version.
> 
> The sources itself are here on github.
> 
> So far I havent a release date, but I think in 1-2 weeks

thank you
