### ISSUE TITLE
hi! i need use FFMPEGExecutor just for to add some self argument to operation ffmpeg,but  the methd FFMPEGLocator.createExecutor just package access,could you change it public access,thanks very much!

### ISSUE THREAD

**Issue by hsj-xiaokang** [a-schild/jave2#66]
hi! i need use FFMPEGExecutor just for to add some self argument to operation ffmpeg,but  the methd FFMPEGLocator.createExecutor just package access,could you change it public access,thanks very much!

**Comment by hsj-xiaokang** [comment]
//i need operation  just like the following code ;but locator.createExecutor() just package access
      FFMPEGLocator locator = new DefaultFFMPEGLocator();
      FFMPEGExecutor ffmpeg = locator.createExecutor();
      ffmpeg.addArgument("some i need self operation here");
      ffmpeg.execute();
      ffmpeg.destroy();

**Comment by a-schild** [comment]
Can you please make a pull request with the changes in it?

**Comment by hsj-xiaokang** [comment]
> Can you please make a pull request with the changes in it?

yes,i have pull request with the changes,please review the code.

**Comment by a-schild** [comment]
Pull request #67 is applied, and the the version published as 2.7.0-SNAPSHOT.
Can you please test this?

**Comment by hsj-xiaokang** [comment]
> Pull request #67 is applied, and the the version published as 2.7.0-SNAPSHOT.
> Can you please test this?
sure, I'd love to.
i have tests but found one thing missing, the FFMPEGExecutor class should also be public so that other packages can access it.
 And the FFMPEGExecutor. Execute () method has a problem, if a CMD command takes more time to execute, it should not end the runtime immediately. I want to add another method FFMPEGExecutor executeWithNotShutDownRuntimeNowAndNotOpenStream (). Please decide on this proposal. 
Thank you very much!

**Comment by a-schild** [comment]
You second pull request is applied.
I did modify the execute() method to have two optional arguments, which specify if the process should be killed on JVM shutdown and if the streams should be attached to the process.

Thus we could remove the executeWithNotShutDownRuntimeNowAndNotOpenStream() method and the duplicate code
