### ISSUE TITLE
We should solve the issue of %TEMP%\jave-2\  .exe already existing when project is running

### ISSUE THREAD

**Issue by goxr3plus** [a-schild/jave2#7]
So after many tests i can see that once the FFMpeg.exe is copied on the destination either the user of the library has to manually delete it or it will be there forever and any time on a future release of the library we will have the same .exe there . So what i recommend .

Currently writing a new DefaultFFMPEGLocator which will have a Date , let's say (21/06/2018) . If the creation date of the .exe is older than the given date , then must be deleted and a new one to be created .

That way everytime we release a new update for Jave2 , let's say the next one 23/06/2018 , it will delete the older .exe files or whatever and replace with the new native files :)

I am interested on your opinion :)

**Comment by goxr3plus** [comment]
At least on my computer : 

```
		if (!temporaryFolder.exists()) {
			temporaryFolder.mkdirs();
			temporaryFolder.deleteOnExit();
		}
```

`temporaryFolder.deleteOnExit();` Never works no matter what i do ..

**Comment by goxr3plus** [comment]
Here is the solution :)  https://github.com/a-schild/jave2/issues/8

**Comment by a-schild** [comment]
The deleteOnExit does not seem to work as intended by the documentation.
