### ISSUE TITLE
如何使用自定义命令

### ISSUE THREAD

**Issue by zuoni1018** [a-schild/jave2#70]
想去除音频空白部分，需要使用自定义命令

**Comment by a-schild** [comment]
English please

**Comment by a-schild** [comment]
Closing because of lack of answers

**Comment by hsj-xiaokang** [comment]
> 想去除音频空白部分，需要使用自定义命令
  //大哥，说英文好不，这是国际化网站，使用如下即可。
  FFMPEGLocator locator = new DefaultFFMPEGLocator();
  FFMPEGExecutor ffmpeg = locator.createExecutor();
  ffmpeg.addArgument("some i need self operation here");
  ffmpeg.execute();
  ffmpeg.destroy();

**Comment by hsj-xiaokang** [comment]
//最新 3.1.1 

DefaultFFMPEGLocator defaultFFMPEGLocator = new DefaultFFMPEGLocator();
ProcessWrapper processWrapper = defaultFFMPEGLocator.createExecutor();

//你需要的自定义的FFmpeg原生命令（比如mp4 转 mp3：ffmpeg -i foo.mp4 foobar.mp3）......
processWrapper.addArgument("ffmpeg -i foo.mp4 foobar.mp3");

//destroyOnRuntimeShutdown表示是否立即关闭Runtime
//如果ffmpeg命令需要长时间执行，destroyOnRuntimeShutdown = false

//openIOStreams表示是不是需要打开输入输出流:
//       inputStream = processWrapper.getInputStream();
//       outputStream = processWrapper.getOutputStream();
//       errorStream = processWrapper.getErrorStream();

//processWrapper.execute() 默认: processWrapper.execute(true,true)
processWrapper.execute(boolean destroyOnRuntimeShutdown, boolean openIOStreams);

//是否执行完毕
int exitCode = processWrapper.getProcessExitCode()

//执行完毕，关闭
processWrapper.destroy();

**Comment by a-schild** [comment]
This Issue is closed, please open a new one and post in english
