### ISSUE TITLE
some problems of using this package

### ISSUE THREAD

**Issue by Semoz** [a-schild/jave2#72]
1. dependency `jave-nativebin-osx64` works on macbook pro 2018, but can not run on macbook 2011, show some error `InputFormatException`
2. when i deploy the project to centos 6.5 use the dependency `jave-native-linux64` and `jave-native-linux32`, both show the error 

```
w.s.jave.DefaultFFMPEGLocator.copyFile:160 Could not find ffmpeg platform executable in resources for <ws/schild/jave/nativebin/ffmpeg-amd64>
```

pls help me,tks :)
---
sorry q2 it's my fault, i used dependency `jave-nativebin-linux64` it works!
q1 i cant not deal
<img width="952" alt="ppppp" src="https://user-images.githubusercontent.com/17057917/71432658-17c87b80-2716-11ea-8117-4efb9dcd87a7.png">

**Comment by a-schild** [comment]
Can you please post the "show some error InputFormatException"

**Comment by mressler** [comment]
This should be closed.
