### ISSUE TITLE
Input/output error

### ISSUE THREAD

**Issue by tengjianlei** [a-schild/jave2#73]
when I used the command ffmpeg -i https://vedio on Linux os,it throws an error named Input/output error.But if I used the same command on Windows 10, it's ok.
for example:ffmpeg version 4.1.3-static https://johnvansickle.com/ffmpeg/ Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzvbi --enable-libzimg
libavutil 56. 22.100 / 56. 22.100
libavcodec 58. 35.100 / 58. 35.100
libavformat 58. 20.100 / 58. 20.100
libavdevice 58. 5.100 / 58. 5.100
libavfilter 7. 40.101 / 7. 40.101
libswscale 5. 3.100 / 5. 3.100
libswresample 3. 3.100 / 3. 3.100
libpostproc 55. 3.100 / 55. 3.100
[tcp @ 0x68a37c0] Failed to resolve hostname oss.cn-north-3.inspurcloudoss.com: Name or service not known
http://oss.cn-north-3.inspurcloudoss.com/vod-cn-north-3-4a41da76-2d73-47a3-b676-9c089f190294/1.SampleAudio_0.4mb5.mp3: Input/output error

**Comment by a-schild** [comment]
What is the URL you are passing to the library?
Is it the host nae which could not be resolved, or something else?

I need a complete example to find the problem.

Can you do a "wget http://oss.cn-north-3.inspurcloudoss.com/vod-cn-north-3-4a41da76-2d73-47a3-b676-9c089f190294/1.SampleAudio_0.4mb5.mp3" on your linux system to retrieve the mp3 file?

Currently it looks like a DNS problem on your linux box

**Comment by tengjianlei** [comment]
the URL is a vedio URL on Internet. I used the command "ffmpeg -i URL" to resolve the vedio on Linux. 
I try to "wget http://oss.cn-north-3.inspurcloudoss.com/vod-cn-north-3-4a41da76-2d73-47a3-b676-9c089f190294/1.SampleAudio_0.4mb5.mp3"  and resolve the local vedio file,it's ok.
Can you resolve a vedio by URL on Linux?

**Comment by a-schild** [comment]
When I extract the ffmpeg-amd64 from the linux64 jar file:

` ./ffmpeg-amd64 -i  http://oss.cn-north-3.inspurcloudoss.com/vod-cn-north-3-4a41da76-2d73-47a3-b676-9c089f190294/1.SampleAudio_0.4mb5.mp3
`

This works.

```
ffmpeg version 4.1.3-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[mp3 @ 0x6cea2c0] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'http://oss.cn-north-3.inspurcloudoss.com/vod-cn-north-3-4a41da76-2d73-47a3-b676-9c089f190294/1.SampleAudio_0.4mb5.mp3':
  Duration: 00:00:27.74, start: 0.000000, bitrate: 128 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
At least one output file must be specified

```

**Comment by tengjianlei** [comment]
Thanks very much

**Comment by mressler** [comment]
@a-schild This should be closed.
