### ISSUE TITLE
jave2哪个版本支持java7？Which version of Jave2 supports java7，Our project is running on java7

### ISSUE THREAD

**Issue by oday-xiexin** [a-schild/jave2#74]
Which version of Jave2 supports java7？Hope to give an answer

**Comment by a-schild** [comment]
I have no version running on java 1.7.
The current version requires java 1.8 as a minimum.

Java 7 is end of life since April 2015, almost 5 years now, so why are you still developing with such an old version?

**Comment by oday-xiexin** [comment]
> I have no version running on java 1.7.
> The current version requires java 1.8 as a minimum.
> 
> Java 7 is end of life since April 2015, almost 5 years now, so why are you still developing with such an old version?
Alas, it's a sad thing. Our development project has been in some years, and I want to realize new functions based on the old technology, which makes me confused. If I upgrade to java8, I can't predict the project risk. The author can help to provide a java7 for us to use.

**Comment by a-schild** [comment]
I could make a java 1.7 version for you, but not for free...

**Comment by oday-xiexin** [comment]
> I could make a java 1.7 version for you, but not for free...

wow,I know it's extra work for you, but I'm still a small intern. I just graduated from university this year, and my current salary may not be able to pay very expensive fees ~ it seems that my current company is unlikely to help me. But I really want to finish this task

**Comment by a-schild** [comment]
In that case, you will have to make this yourself.

Mainly you will need to set the java version to 1.7 in the maven files and then compile verything and then look which parts of the code are java 1.8 specific and then rewrite them.

If you wish, I could create a branch where you could make a pull request for a java 7 version of the libraries

**Comment by oday-xiexin** [comment]
> In that case, you will have to make this yourself.
> 
> Mainly you will need to set the java version to 1.7 in the maven files and then compile verything and then look which parts of the code are java 1.8 specific and then rewrite them.
> 
> If you wish, I could create a branch where you could make a pull request for a java 7 version of the libraries

Oh, I'll look at the source code after work. Within my ability, I'll try to rewrite some of them. I want to ask some powerful authors. Can you recall how few sentences involve java8 writing at present? If it's a lot, it's sad. I'm still a rookie

**Comment by lsjspl** [comment]
jdk升级到java8不完事了 向下兼容的。

**Comment by a-schild** [comment]
@lsjspl can you please also put your answers in english too? I can't read your language.
Thanks
