### ISSUE TITLE
Do you support Android (os Linux arch i686)?

### ISSUE THREAD

**Issue by fmiguelmmartins** [a-schild/jave2#76]
Are there any plans to support Android? Thanks!

**Comment by a-schild** [comment]
Not at the moment.
But if you are willing to provide a pull request we would integrate it.

Can we execute binaries under Android?
If yes:
I think it should be enough to enhance DefaultFFMPEGLocator.java to detect the correct platform and integrate the correct ffmpeg binaries. 

If no:
Then I think you need to google for another ffmpeg android library.
Also on github you find various project for ffmpeg an android, but I have no expirience with any of them

**Comment by fmiguelmmartins** [comment]
Thanks mate! Yup, I am working on something at the moment so I maybe by next week I will submit something! Thanks for replying :)

**Comment by mressler** [comment]
@fmiguelmmartins Any update on progress?
