### ISSUE TITLE
Java file path is not compatible with linux file path

### ISSUE THREAD

**Issue by Ryanznoco** [a-schild/jave2#77]
For example, if the file name contains "(", it will need to be escaped in the linux command. The current version will report “No such file or directory“.

**Comment by a-schild** [comment]
I will happily integrate a pull request ;)

**Comment by Ryanznoco** [comment]
Sorry i said wrong, Runtime#exec will automatically escape for us.
@see java.lang.ProcessImpl#createCommandLine
@see java.lang.ProcessImpl#needsEscaping
