### ISSUE TITLE
Lack of -loop flag for ffmpeg

### ISSUE THREAD

**Issue by chrysophylax** [a-schild/jave2#78]
To support the use case of generating videos from still images, the -loop flag should be added `-loop 1` per ffmpeg docs.

Currently, this flag is not exposed in EncodingAttributes.

Sanity checks:
This flag should co-occur with a durationAttribute or the encoding will loop forever.

**Comment by a-schild** [comment]
Can you point me to the ffmpeg doc loecation?
I only see -stream_loop here https://ffmpeg.org/ffmpeg.html#toc-Main-options

**Comment by a-schild** [comment]
Your merge request is included in the 2.8.0-SNAPSHOT release.
Can you please test it and giveok for a final release if everything is OK?

Thanks for your submission

**Comment by mressler** [comment]
Seems like this should be closed.

**Comment by mressler** [comment]
Closing, because this looks like it's completed.
