### ISSUE TITLE
Does it support linux-arm64？

### ISSUE THREAD

**Issue by wslin1994** [a-schild/jave2#89]
CentOS7.4
arm 64

**Comment by a-schild** [comment]
At the moment not, but if you can tell me what platform is detected, we can add it.
Can you please tell me what these two calls return on the arm64 platform?

```
String os = System.getProperty("os.name").toLowerCase();
String arch = System.getProperty("os.arch");
```

**Comment by wslin1994** [comment]
> At the moment not, but if you can tell me what platform is detected, we can add it.
> Can you please tell me what these two calls return on the arm64 platform?
> String os = System.getProperty("os.name").toLowerCase();
> String arch = System.getProperty("os.arch");
![image](https://user-images.githubusercontent.com/22786603/87658515-e46f3c00-c78e-11ea-9911-a782729deea1.png)
os:linux
arch:aarch64

CentOS Linux release 7.6.1810 (AltArch)

**Comment by wslin1994** [comment]
![image](https://user-images.githubusercontent.com/22786603/87658629-0e286300-c78f-11ea-8f51-c83a4534fe67.png)
Thinks

**Comment by a-schild** [comment]
Can you try the 2.8.0-SNAPSHOT release please?
```
        <dependency>
            <groupId>ws.schild</groupId>
            <artifactId>jave-core</artifactId>
            <version>2.8.0-SNAPSHOT</version>
        </dependency>    
        <dependency>
            <groupId>ws.schild</groupId>
            <artifactId>jave-nativebin-linux-arm64</artifactId>
            <version>2.8.0-SNAPSHOT</version>
        </dependency>    
```

**Comment by a-schild** [comment]
@wslin1994 Did you have time to check if it's working?
I would like to do a final release of the 2.8.0 before we start going on toward 3.x

**Comment by wslin1994** [comment]
@a-schild    sorry,I can't download this dependency.
<dependency>
            <groupId>ws.schild</groupId>
            <artifactId>jave-core</artifactId>
            <version>2.8.0-SNAPSHOT</version>
        </dependency>    
        <dependency>
            <groupId>ws.schild</groupId>
            <artifactId>jave-nativebin-linux-arm64</artifactId>
            <version>2.8.0-SNAPSHOT</version>
        </dependency>

**Comment by a-schild** [comment]
I did reupload them.
Do you have specified the snapshot repository location as required here:

https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository

The drirect link if not using maven:
https://oss.sonatype.org/#view-repositories;snapshots~browsestorage

**Comment by mressler** [comment]
@a-schild This should be closed unless new information surfaces.

**Comment by mressler** [comment]
No new information surfaced.
