### ISSUE TITLE
Windows 64 and 32 have no native FFMPEG at all inside , maybe forgot ?

### ISSUE THREAD

**Issue by goxr3plus** [a-schild/jave2#9]
Windows 64 and 32 have no native FFMPEG at all inside , maybe forgot ? I just saw it.... Linux 32 and Linux64 have though :)

Hope you fix it soon :)

**Comment by goxr3plus** [comment]
This is very funny for some reason .... lol all have except Jave Native Windows 64 and Jave Native Windows 32

**Comment by a-schild** [comment]
Can you try with the current head (2.4.1-SNAPSHOT)?

I have renamed the packages into the ws.schild.jave namespace and I'm looking in publishing them in maven central

**Comment by goxr3plus** [comment]
Yes of course :)

**Comment by goxr3plus** [comment]
So i updated the fork that i have for your project and now everything works like charm it's amazing !!! Look :+1: 

Look on JitPack : https://jitpack.io/#GOXR3PLUS-STUDIO/jave2/2.4.1
The repository i have forked your project : https://github.com/GOXR3PLUS-STUDIO/jave2

The below downloads only the WIndows64 needed jars .

``` XML
		<dependency>
			<groupId>com.github.GOXR3PLUS-STUDIO.jave2</groupId>
			<artifactId>jave-all-deps</artifactId>
			<version>2.4.1</version>
			<exclusions>
				<exclusion>
					<groupId>com.github.GOXR3PLUS-STUDIO.jave2</groupId>
					<artifactId>jave-native-win32</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.github.GOXR3PLUS-STUDIO.jave2</groupId>
					<artifactId>jave-native-linux32</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.github.GOXR3PLUS-STUDIO.jave2</groupId>
					<artifactId>jave-native-linux64</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.github.GOXR3PLUS-STUDIO.jave2</groupId>
					<artifactId>jave-native-osx64</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

**Comment by goxr3plus** [comment]
In short it downloads the below files :+1: 

![screenshot_2](https://user-images.githubusercontent.com/20374208/42064794-64517dcc-7b40-11e8-9bb5-a6e23b7b01e2.jpg)


We must get rid of ```commons logging api``` , i am not that good on logging yet  though :)

**Comment by a-schild** [comment]
What is your problem with the commons logging api?
We can either use the JDK provided logging, but then you are limited to use this in all projects which use jave.
Most open source code bases use the commons-logging-api to give the users of the libraries the choice which logging backend they wish to use. Also used is the SLF4J logging facade, if you prefer this one we can switch to it.

But I won't use System.out.println or a direct dependency to a specific logging system.

https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html
https://tomcat.apache.org/tomcat-8.0-doc/logging.html

**Comment by goxr3plus** [comment]
What improvements we can do in this repository :) ? How i can help further :)

**Comment by goxr3plus** [comment]
This is fixed so i close this issue :)
